### ISSUE TITLE
Better error reporting for semantic analysis

### ISSUE THREAD

**Issue by electrum** [facebook/presto#1055]
The current error reporting does not give any indication about which part of the query is invalid. This is problematic on tables with many columns, especially when they all have the incorrect type (i.e. every column is a string):

    presto:default> select 123 = 'foo';
    Query ... failed: Types are not comparable with '=': bigint vs varchar

**Comment by cberner** [comment]
Fixed by: https://github.com/facebook/presto/pull/3980
