### ISSUE TITLE
Per query/session settings

### ISSUE THREAD

**Issue by snarayananqubole** [facebook/presto#1062]
It would be useful to have a per query / per session settings mechanism that can be used to control optimizations and other functionality.

- Surface: SET var = literval;
- literal can be string, integer, double, duration, memory (mb/gb), boolean
- Varname must be in a whitelist, else SET statement will error (this is unlike Hive, but like most other DBs)
- The parameters are available to optimization, execution and metadata components

**Comment by cberner** [comment]
We added session parameters a while back
