### ISSUE TITLE
Default read timeout for HttpClients too large

### ISSUE THREAD

**Issue by dain** [facebook/presto#1085]
The default read timeout for HttpClient is 1minutes.  Most remote interactions in Presto are short and automatically retired, so a long timeout is counterproductive.  A shorter timeout will allow Presto to detect failed queries much faster and free up resources.

**Comment by cawallin** [comment]
@dain: looks like the fix for this went in, this can probably be closed

**Comment by cawallin** [comment]
@cberner would you mind closing this, if applicable?
