### ISSUE TITLE
Task stuck in PLANNING state

### ISSUE THREAD

**Issue by martint** [facebook/presto#1138]
There's some weird bug in the coordinator that results in queries getting stuck. The symptoms are:
- One or more tasks for a query in state PLANNING
- Other tasks get splits assigned and make progress
- Worker associated with that task doesn't receive any HTTP requests for status updates or split assignment for the task
- Restarting the worker doesn't seem to fix the issue
- Restarting the coordinator "fixes" it.

**Comment by cberner** [comment]
This was fixed by upgrading to the latest Jetty
