### ISSUE TITLE
Add error codes to Presto UI

### ISSUE THREAD

**Issue by cberner** [facebook/presto#1166]
Update UI to display error codes:

* On the main page, add a new "Error" column to the completed query table that contains a shorter version of the `ErrorType` (category) of the error code: USER, INTERNAL, RESOURCES, EXTERNAL
* On the detail page, add the error code (name and code value). Example: `EXCEEDED_MEMORY_LIMIT (131073)`

**Comment by kadaan** [comment]
This has been fixed, right?  Is so, could this be closed?
