### ISSUE TITLE
Different invalid partition handling behavior between Presto and Hive

### ISSUE THREAD

**Issue by zhenxiao** [facebook/presto#1431]
Hive and Presto have different behavior when handling invalid partition. Presto will throw an exception, while, Hive will parse the partition as null.

for example, if a table t is partitioned by int, and there is an invalid partition with partition key not valid:
partition=%3D20111102

in hive, hive will treat this as a partition with partition key null
in presto, presto will throw an exception, 
java.lang.NumberFormatException: For input string: "=20111102"

Shall we treat this as a user invalid data problem, or shall we patch presto to have the same behavior as hive?

Any comments or suggestions are appreciated.

**Comment by cberner** [comment]
I think this should be fixed now. Please re-open if you still see it
