### ISSUE TITLE
Support for multiple metastore URIs for High Availability

### ISSUE THREAD

**Issue by fluential** [facebook/presto#1434]
In hive-site.xml hive.metastore.uris property can have a comma separated list when your cluster has multiple Hive Metastore servers.
It would be great if presto support that as well.

**Comment by cawallin** [comment]
I'm going to take this up.

**Comment by electrum** [comment]
We actually support this today with `DiscoveryLocatedHiveCluster`. It has code for connecting to multiple metastore services. The discovery version has the advantage of being dynamic, since you can add/remove services at runtime via the discovery API. Though I've considered removing it since no one uses it...

**Comment by nezihyigitbasi** [comment]
@electrum This would be a useful feature if Presto was able to connect to multiple metastore services, and fallback to the other one when one fails. Is it currently possible to create such a configuration with Presto?

**Comment by cawallin** [comment]
From what I can see, Presto shuffles all of the metastores it has descriptors for and goes through sequentially trying them.  So, there is fallback.  This does not quite match the behavior that Hive uses, though, which is to default to using the first metastore URI specified in the list, and then to fail over to a random URI in the list if it can't connect to the first metastore, continuing to try the fallback URIs until it is able to connect (see http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/admin_ha_hivemetastore.html).  I guess the ServiceDescriptor for the hive-metastore that is the default one could have a 'default' property or something like that?

**Comment by nezihyigitbasi** [comment]
@cawallin What I mean by fallback is a fallback mechanism among multiple Hive metastores for the same catalog, is it really possible? I though it isn't now. If it is, how can I specify it in the catalog properties file?

**Comment by cawallin** [comment]
@nezihyigitbasi I don't think you can specify it in the catalog properties file -- you have to set your hive.metastore.uri to something with the schema discovery, and then set up your metastores via the discovery server. I'm still looking into how that works, though.

**Comment by cawallin** [comment]
Made a PR for adding multiple metastore support to the catalog properties file; I tried for a while to get the discovery-based Hive to work, but couldn't get the static announcements to work to tell the discovery server about your metastores. I might look into it more later though.
