### ISSUE TITLE
Cassandra plugin doesn't support timeuuid functions.

### ISSUE THREAD

**Issue by pgarrison** [facebook/presto#1491]
When using cassandra, the [CQL timeuuid functions](http://www.datastax.com/documentation/cql/3.0/cql/cql_reference/timeuuid_functions_r.html), in particular unixTimestampOf, are not available. This renders the timeuuid type unusable.

    Query 20140714_201618_00009_i6x7m failed: Function unixtimestampof not registered

**Comment by heiko-braun** [comment]
@pgarrison did you actually implement the FunctionFactory to convert timeuuid fields?

**Comment by pgarrison** [comment]
Nope, sorry, I've stopped working on the project I needed it for.
