### ISSUE TITLE
Cassandra String based partition keys

### ISSUE THREAD

**Issue by AndreasPetter** [facebook/presto#1518]
While improving the cassandra catalog towards pushing down predicates with clustering keys i noticed that String-based partition keys are not working for me right now. They show up as a type mismatch of Strings with Slices. Reproducable by e.g.:
`select count(*) from timedindex where key='abc';`
I fixed that by changing various methods like Marker.getValue (returning toUtf8String if it's a Slice), but probably this is not the right way as there might be slices with different types in it?

**Comment by toxeh** [comment]
@cberner , this issue seems to be closed.
