### ISSUE TITLE
Encountered too many errors talking to a worker node.

### ISSUE THREAD

**Issue by lvxin1986** [facebook/presto#1704]
when i run 3 independent queries in parallel, one of the queries reports errror like:

com.facebook.presto.spi.PrestoException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes (http://192.168.177.88:8090/v1/task/20140922_100923_00016_bj6yn.1.3 - 16 failures, time since last success 2.00m)

my cluster is composed of  40 nodes, and each node' hardware has 128G RAM ,32 cores cpu and 24T disk.

the relevant tables of problem query  are :
sjtmp.orders_base                 txt                   408,730,667          95.1 G
sjtmp.orderamount_base       txt                   627,768,383          123.6 G
sjtmp.finbill_base                    txt                   366,653,551          166.6 G
sjtmp.fasresult_base              txt                   145,328,730           43.8 G
cwsj.OrderExpend_Pop          txt                   221,763,035           20.5 G
cwsj.OrderExpend_Pop_his    txt                   324,720,090           30.2 G
cwsj.orderamountexpand        txt                  1,131,906,931         87.5 G

and the problem query sql is :
SELECT oo.id,oo.youhui,oo.totalprice, oo.shopcoupon,oo.payment ,oo.createDate,oo.jyn,oo.sendpay,
        oo.venderpre,oo.balance,oo.MobileDiscount,pop.rf_bill_id,pop.bal,pop.order_id,pop.VENDER_ID,
        case when tjtype=0 then oo.totalPrice - COALESCE(oo.venderpre,0)-COALESCE(oo.shopcoupon,0)-COALESCE(pop.bal,0) 
        when tjtype=1 then COALESCE(oo.youhui,0)-COALESCE(oo.venderpre,0)-COALESCE(oo.shopcoupon,0)+COALESCE(balance,0)+COALESCE(MobileDiscount,0)-COALESCE(pop.BAL,0)
        end as chayi
        FROM (
                select a.Id,a.youhui,a.totalprice,a.payment,max(a.createDate) createDate,a.jyn,a.sendpay,
                case when a.jyn = 22 and a.payment IN ('1','3','12') and substr(a.sendpay,32,1)='2' then 1 else 0 end as tjtype,
                sum(cast(reprice as double)+cast(discount as double)+cast(MoneyOfSuit as double)) as venderpre,SUM(cast(MoneyBalance as double)) balance,
                SUM(cast(MobileDiscount as double)) as MobileDiscount,sum(shopcoupon) shopcoupon     
                from (
                        select pra.id,pra.youhui, pra.totalPrice, pra.createDate, pra.STATE, pra.jyn,pra.payment,pra.parentid,pra.ztdate,pra.sendpay,pra.venderId,pra.orderamountid,pra.Skuid,
                        pra.Orderid,pra.reprice,pra.discount,pra.moneyofsuit,pra.MoneyBalance,pra.MobileDiscount,shopcoupon 
                        from (
                                SELECT a.id, a.youhui, a.totalPrice, a.createDate, a.STATE, a.jyn,a.payment,a.parentid,a.ztdate,a.sendpay,a.venderId,b.Id as orderamountid,b.Skuid,
                                b.Orderid,b.reprice,b.discount,b.moneyofsuit,b.MoneyBalance,b.MobileDiscount
                                FROM (
                                    SELECT id, youhui, totalPrice, createDate, STATE, jyn,payment,parentid,ztdate,sendpay,venderId 
                                    FROM (
                                        SELECT oo.id, oo.youhui, oo.totalPrice, oo.createDate, oo.state, oo.jyn,oo.payment,oo.parentid,oo.ztdate,sendpay,pop.venderId 
                                        FROM (
                                            SELECT id, youhui, totalPrice, createDate, STATE, jyn,payment,parentid,ztdate,sendpay 
                                            FROM  sjtmp.Orders_base a 
                                            WHERE STATE = 1  
                                            AND  jyn  IN (21,22,23,24,25)        
                                            AND ztdate >= '2014-04-01' 
                                            AND ztdate < '2014-07-01'  
                                        ) oo 
                                        left outer join  (
                                            select venderId,orderId from presto.OrderExpend_Pop
                                            union all 
                                            select venderId,orderId from presto.OrderExpend_Pop_his 
                                        )  pop 
                                        ON oo.id = pop.orderId 
                                    ) t
                                    WHERE venderId <> 51061 or venderid is null
                                )  a  
                                left outer join(   
                                    select om.Orderid,om.skuid,id,reprice,discount,MoneyOfSuit,MoneyBalance,MobileDiscount
                                    from sjtmp.orderamount_base om 
                                    where om.Status=1 
                                )b   
                                ON a.id=b.orderid
                            ) pra
                            left outer join (  
                                select orderid,skuid,OrderAmountId,SUM(amount) as shopcoupon 
                                from presto.orderamountexpand
                                where Type in (3,4)   
                                group by orderid,skuid,OrderAmountId
                            ) ome  
                            on pra.id=ome.OrderId and pra.skuid=ome.Skuid and pra.orderamountid=ome.OrderAmountId
                    ) a
                 group by a.Id,a.youhui,a.totalprice,a.payment,a.jyn,a.sendpay  
        ) oo 
        left outer join (  
            SELECT rf_bill_id, SUM(direction*bal) AS bal,order_id,VENDER_ID 
            FROM  (
                SELECT rf_bill_id,cast(direction as bigint) as direction, cast(bal as double) as bal,order_id,VENDER_ID
                FROM sjtmp.finbill_base
                WHERE ORDER_STATUS = '19'
                AND SERVICE_FEE_TYPE ='30'
                AND rf_bill_type ='0' 
                UNION ALL
                SELECT rfid as rf_bill_id,vardirection*(-1) as direction, cast(amount as double) as bal,cast(orderid as varchar) as order_id,supplierID as VENDER_ID
                FROM sjtmp.fasresult_base
                WHERE  feetypeid =30
            )p
            GROUP BY rf_bill_id,order_id,VENDER_ID 
        ) pop 
        ON oo.id = cast(pop.order_id as bigint)
        WHERE (tjtype=0 and abs(totalPrice - COALESCE(oo.venderpre,0)-oo.shopcoupon-cast(pop.BAL as double))>0.01)
            or (tjtype=1 and abs(COALESCE(oo.youhui,0)-COALESCE(oo.venderpre,0)-oo.shopcoupon+COALESCE(balance,0)+COALESCE(MobileDiscount,0)- cast(pop.BAL as double))>0.01 
            OR pop.order_id IS NULL);

I doubt whether the presto can handle the big table with join and goup by operation ?

any suggestion is appreciative.

**Comment by cberner** [comment]
That's usually caused by a full GC on the worker. I would suggest using the G1 collector. We've also fixed a lot of stability issues recently, so if you're still seeing this with the current release and it's not GC related, please re-open!

**Comment by syed72** [comment]
Iam facing same issue, how can i solve this issue?
Thanks

**Comment by dabaitu** [comment]
hi @cberner - I'm running 0.151 and have configured G1 collector but I'm still seeing this error.

**Comment by cberner** [comment]
There are many reasons that might happen. Could you provide more details about your setup? Like available network bandwidth, amount of memory on workers, heap size on workers, setting for `query.max-memory` and `query.max-memory-per-node`? Also, if you enable GC logging, do you see any full GCs happening on the workers?

**Comment by dabaitu** [comment]
@cberner - sorry for the late response. Here's our config:
cluster: each machine has 56 cores, but only 64GB ram. 189 workers(not counting coordinator).

worker config:
 query.initial-hash-partitions=200
 query.max-memory=500GB
 query.max-memory-per-node=18GB
 exchange.http-client.request-timeout=120s
 exchange.http-client.idle-timeout=10s
 task.max-worker-threads=53

There was a problem in 0.151 for us that we are still trying to understand, so we rolled back to 0.143. I haven't seen any full GCs happening.

**Comment by cberner** [comment]
@dabaitu 0.151 was released with a bad HTTP library, if I recall correctly. I would upgrade to 0.152.1

**Comment by dabaitu** [comment]
@cberner I just tried building 0.152.1, wonder if you have a quick solution for:

[ERROR] Found a problem with the dependency org.eclipse.jetty.http2:http2-client
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: com.facebook.presto:presto-client, io.airlift:discovery, io.airlift:event, io.airlift:http-client, io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty.http2:http2-common
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: com.facebook.presto:presto-client, io.airlift:discovery, io.airlift:event, io.airlift:http-client, io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty.http2:http2-hpack
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: com.facebook.presto:presto-client, io.airlift:discovery, io.airlift:event, io.airlift:http-client, io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty.http2:http2-http-client-transport
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: com.facebook.presto:presto-client, io.airlift:discovery, io.airlift:event, io.airlift:http-client, io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty.http2:http2-server
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty:jetty-alpn-client
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: com.facebook.presto:presto-client, io.airlift:discovery, io.airlift:event, io.airlift:http-client, io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty:jetty-client
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: com.facebook.presto:presto-client, io.airlift:discovery, io.airlift:event, io.airlift:http-client, io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty:jetty-http
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: com.facebook.presto:presto-client, io.airlift:discovery, io.airlift:event, io.airlift:http-client, io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty:jetty-io
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: com.facebook.presto:presto-client, io.airlift:discovery, io.airlift:event, io.airlift:http-client, io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty:jetty-jmx
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty:jetty-security
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty:jetty-server
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty:jetty-servlet
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx-http
[ERROR] Found a problem with the dependency org.eclipse.jetty:jetty-util
  Resolved version is 9.3.9.M1
  Version 9.3.11.v20160721 was expected by artifact: io.airlift.discovery:discovery-server
  Version 9.3.9.M1 was expected by artifacts: com.facebook.presto:presto-client, io.airlift:discovery, io.airlift:event, io.airlift:http-client, io.airlift:http-server, io.airlift:jaxrs, io.airlift:jmx, io.airlift:jmx-http

**Comment by haozhun** [comment]
@dabaitu Use 72e85e0 (one commit ahead of 0.152.1)
