### ISSUE TITLE
Presto's tests are very flaky

### ISSUE THREAD

**Issue by brndnmtthws** [facebook/presto#1713]
Some of the tests in Presto are flaky and fail randomly.  It's difficult to contribute code because I have to manually switch off all tests except for the module I'm working on (`presto-client`, for example, fails 100% of the time on my machine).

If you look at the build history in travis, you can also see a long continuous streak of failure on `master`: https://travis-ci.org/facebook/presto/builds

From the travis log, it looks like one frequent failures is tests being OOM killed.  Travis provides 3GB of memory for building, which should be sufficient.  However, the heap size + perm gen for maven and the tests exceeds the total available memory.

For now, I propose doing this to make the build succeed: https://github.com/facebook/presto/pull/1712

**Comment by cberner** [comment]
I spent a while fixing our tests, and tracked down several race conditions. If you're still having problems try setting the surefire thread count to 1

**Comment by brndnmtthws** [comment]
Good work!
