### ISSUE TITLE
Non-equi joins not supported

### ISSUE THREAD

**Issue by yuananf** [facebook/presto#1742]
We met some problems when using presto, first one is like this:

presto:fdm> SELECT    at1.NewIdCompany AS NewIdCompany ,
         ->           sbd.StoreAttr AS storeId ,
         ->           atd.price AS price
         ->           FROM AFS_Transfer AS at 
         ->           JOIN AFS_TransferDetail AS atd  ON atd.rfid = at.Transfer_id
         ->           left join (
         ->                SELECT atd2.idpart
         ->                 FROM   AFS_TransferDetail AS atd2 
         ->                 JOIN AFS_Transfer AS at2  ON at2.Transfer_id = atd2.rfid
         ->                         AND at2.Type IN ( 1, 5, 19 )
         ->                 WHERE at2.FromTime > at.FromTime
         ->                  AND at2.Status > 0 
         ->           ) on atd2.idpart = atd.idpart
         ->           WHERE     at.Status < 1;
Query 20140930_091504_00087_p35bg failed: Non-equi joins not supported: ("at2"."type" IN (1, 5, 19))

We saw that presto does not support Non-equi joins now, so we put the condition to where clause. But then is another problem, like this:

presto:fdm> SELECT at1.NewIdCompany AS NewIdCompany ,
         ->        sbd.StoreAttr AS storeId ,
         ->        atd.price AS price
         -> FROM AFS_Transfer AS AT
         -> JOIN AFS_TransferDetail AS atd ON atd.rfid = AT.Transfer_id
         -> LEFT JOIN
         ->   ( SELECT atd2.idpart
         ->    FROM AFS_TransferDetail AS atd2
         ->    JOIN AFS_Transfer AS at2 ON at2.Transfer_id = atd2.rfid   
         ->    WHERE  at2.Type IN (1,5,19)
         ->      AND at2.FromTime > AT.FromTime
         ->      AND at2.Status > 0) 
         ->   ON atd2.idpart = atd.idpart
         -> WHERE AT.Status < 1;
Query 20140930_092458_00092_p35bg failed: Column 'at.fromtime' cannot be resolved

So it seems that presto subquery does not recognise the outer Aliases.
Is this a bug?

**Comment by cberner** [comment]
Merging with https://github.com/facebook/presto/issues/2050
