### ISSUE TITLE
Support CUBE / ROLLUP / GROUPING SETS

### ISSUE THREAD

**Issue by electrum** [facebook/presto#1851]
Details here:
http://www.postgresql.org/docs/devel/static/queries-table-expressions.html#QUERIES-GROUPING-SETS
http://www.postgresql.org/docs/devel/static/functions-aggregate.html#FUNCTIONS-GROUPING-TABLE

**Comment by joy-yao** [comment]
The link above is gone.

**Comment by electrum** [comment]
I updated the links. Looks like this feature will be in PostgreSQL 9.5, which will make testing easier.

**Comment by justinjose28** [comment]
Any tentative date for this new feature in presto?

**Comment by cberner** [comment]
Nothing concrete, but we tentatively plan to have someone work on this before the end of the year
