### ISSUE TITLE
Implement CORR, COVAR_*, etc. aggregation functions

### ISSUE THREAD

**Issue by martint** [facebook/presto#1854]
From the SQL specification, section 4.15:

> The binary aggregate functions take a pair of arguments, the `<dependent variable expression>` and the `<independent variable expression>`, which are both `<numeric value expression>`s. Any row in which either argument evaluates to the null value is removed from the group. If there are no rows remaining in the group, then the result of REGR_COUNT is 0 (zero), and the other binary aggregate functions result in the null value. Otherwise, the computation concludes and the result is:
> [...]
> - If COVAR_POP is specified, then the population covariance, defined as the sum of products of the difference of `<independent variable expression>` from its mean times the difference of `<dependent variable expression>` from its mean, divided by the number of rows remaining.
> -  If COVAR_SAMP is specified, then the sample covariance, defined as the sum of products of the difference of `<independent variable expression>` from its mean times the difference of `<dependent variable expression>` from its mean, divided by the number of rows remaining minus 1 (one).
> - If CORR is specified, then the correlation coefficient, defined as the ratio of the population covariance divided by the product of the population standard deviation of `<independent variable expression>` and the population standard deviation of `<dependent variable expression>`.
> - If REGR_SLOPE is specified, then the slope of the least-squares-fit linear equation determined by the (`<independent variable expression>`, `<dependent variable expression>`) pairs.
> - If REGR_INTERCEPT is specified, then the y-intercept of the least-squares-fit linear equation determined by the (`<independent variable expression>`, `<dependent variable expression>`) pairs.

**Comment by haozhun** [comment]
Fixed by #2772
