### ISSUE TITLE
How does approx_percentile work for doubles?

### ISSUE THREAD

**Issue by dhruvbird** [facebook/presto#1898]
Martin says that some bit-tricks are used to make this work. This seems to be where it happens: https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/aggregation/ApproximateDoublePercentileAggregations.java#L74

However, -ve numbers (sign bit == 1) will enter the digest to the right of positive numbers. Maybe I'm missing something.

**Comment by cberner** [comment]
It's converting the doubles into lexicographically comparable long values. It's just reorganizing the bits in the IEEE754 double
