### ISSUE TITLE
Approx_distinct optimization (memory + performance)

### ISSUE THREAD

**Issue by FlxRobin** [facebook/presto#1920]
Hi there,

We have recently been testing with automatically rewriting queries in our abstraction layer, before submitting them to presto. What we do is the following:

Estimate the amount of uniques that will end up in an approx_distinct(x) operation. If this is lower in terms of memory (thus < 2048 bytes which the registers of a HyperLogLog (HLL) object use), we use regular count(distinct x)

For low cardinality this seems to work a lot better. Not a real benchmark, but our own query execution time dropped sometimes over 2x.

We could also build this logic into presto, where all approx_distinct(x) start as a regular one, and as soon as they approach the 2048 bytes, we create a HLL object and stream through the items in our "distinct list". 

This will work really well on queries that run a lot of approx_distinct(x) registers on a high number of dimensions which have to be aggregated.

What do you think?

**Comment by cberner** [comment]
Please re-open if this is still an issue for you. We completely rewrote the `approx_distinct` code recently
