### ISSUE TITLE
Support Hive DECIMAL type in Hive connector

### ISSUE THREAD

**Issue by andytinycat** [facebook/presto#1990]
As far as I can see, there's no support for the Hive DECIMAL type.

It looks like Presto's Hive connector is based at Hive 0.9, which doesn't have support for this type. Support was added in 0.11, which was released in mid-2013.

At present, Presto skips DECIMAL columns (again, correct me if I'm wrong) when reading tables through the Hive connector - the column doesn't appear in a DESCRIBE or SELECT.

Either the columns should be coerced into one of the available types (e.g. double), or native support should be added.

I'm happy to attempt this, but after a brief browse of the codebase, and the hard dependency on Hive 0.9, I'm not sure how to go about it without some guidance.

**Comment by cberner** [comment]
https://github.com/facebook/presto/issues/2797

**Comment by fmeiser** [comment]
As a first step presto could use double/long as internal representation for DECIMAL.

**Comment by cberner** [comment]
Superseded by: https://github.com/facebook/presto/issues/2797
