### ISSUE TITLE
empty result on hive table with integer partition keys

### ISSUE THREAD

**Issue by theJohnnyBrown** [facebook/presto#2029]
Hi presto folks, thanks for this excellent tool.

We have a table in hive, stored in S3, that looks like below. 

```sql
create external table IF NOT EXISTS hourly_stats
      (date_id int,
       build string,
       version string,
       run string,
       count int,
       avg double,
       min double,
       max double,
       sum double,
       p_25th double,
       p_50th double,
       p_75th double,
       p_90th double,
       p_95th double,
       p_99th double,
       stddev double
       ) PARTITIONED BY (stack string, year int, month int, day int, hour int)
       stored as sequencefile
       LOCATION 's3n://BUCKET-NAME;
```

Queries from a hive cluster running on EMR return data, and the table name appears in `show tables` in presto, but querying it in presto returns no rows. Someone at Qubole support informed us that presto might not be able to handle integer partition keys, so we created another table, identical except partitioned by strings.

```sql
create external table IF NOT EXISTS presto_hourly_stats
      (date_id int,
       alm_build string,
       alm_version string,
       alm_run string,
       service string,
       metric string,
       count int,
       avg double,
       min double,
       max double,
       sum double,
       p_25th double,
       p_50th double,
       p_75th double,
       p_90th double,
       p_95th double,
       p_99th double,
       stddev double
       ) PARTITIONED BY (stack string, year string, month string, day string, hour string)
       stored as sequencefile
       LOCATION 's3n://BUCKET-NAME;

from   hourly_stats
insert overwrite TABLE presto_hourly_stats partition (stack, year, month, day, hour)
from   hourly_stats
insert overwrite TABLE presto_hourly_stats partition (stack, year, month, day, hour)
select date_id, build, version, run, service, metric, count, avg, min, max, sum, p_25th, p_50th, p_75th, p_90th, p_95th, p_99th, stddev, stack, year, month, day, hour;
```

Querying this table with presto seems to work fine. Haven't done anything special to the hdfs config except to add the AWS key id and secret to core-site.xml.

Are integer partition keys not supported? Am I doing something wrong? Is there any more info that would help you reproduce the problem?

Thanks

**Comment by nezihyigitbasi** [comment]
@theJohnnyBrown recently we hit a similar problem. In our case we have an int partition named ``hour`` and when we query from Presto, say for ``hour=1``, we don't get any rows because the partition ``hour=1`` didn't exist in the metastore while ``hour=01`` did. Seems like hive metastore keeps the partition names all as strings in the backend db and AFAIK there is no way to query those partitions from Presto unless we change the type of the ``hour`` field from int to string, or update the partition name from ``hour=01`` to ``hour=1``. I would be curious to know if someone has a nice workaround for this issue.

**Comment by snarayananqubole** [comment]
This is the original thread on the subject:
https://groups.google.com/forum/#!searchin/presto-users/integer$20partition$20type/presto-users/nrHPG6Yr0ho/62ZasBfPv4MJ

We fixed this internally recently. Will start a PR for it.

**Comment by cberner** [comment]
I think https://github.com/facebook/presto/pull/2244 should fix this. Please re-open, if not
