### ISSUE TITLE
non-equi join for left(right) join?

### ISSUE THREAD

**Issue by yuananf** [facebook/presto#2050]
Hi, I tested the feature of simple non-equi join, it works fine for inner join as I expected.
I'd like to know is there any plan to support non-equi left join and non-equi right join?
It will be really helpful to me! 
Thanks!
@cberner

**Comment by dilipkasana** [comment]
@yuananf Hi,We are also having same problem and looking for resolution .We have dependency on this.We have lot of queries like SELECT * FROM table1 LEFT JOIN table2 ON table1.id=table2.id AND table1.date_added > table2.date_added. We need all the rows of table1.We have several such queries.    Can you please explain a bit the way you are going to resolve this. Thanks in advance.Any help will be appreciated.

**Comment by yuananf** [comment]
I'm not working on it now, but you may want to modify the SQL so that presto can run it correctly.

For example, 
----------------------------Origin SQL-------------------------------
SELECT table1.id, table1.date_added, table2.date_added
FROM table1
LEFT JOIN table2 ON table1.id=table2.id
AND table1.date_added > table2.date_added

----------------------------Modified SQL-------------------------------
SELECT a.id, a.date_added, b.date_added
FROM table1 a
LEFT JOIN
(SELECT table1.id, table2.date_added
FROM table1 
JOIN table2 ON table1.id=table2.id
WHERE table1.date_added > table2.date_added) b
ON a.id = b.id

This may not be fully correct, you can modify it as you wanted.
I modified my SQL like this and it works fine.

Good luck!

**Comment by dilipkasana** [comment]
@cberner @electrum @dain  I have extended equi join to work for left/right non equi join,using already implemented equi join support.As for inner non-equi join,presto push down filters to where clause,And so in case of right/left join,It will not work so push filters to a generated class  and call it from  from LookUpJoinOperator for left and right join non equi condition.I have testes this and working fine. The logic is same here first hash on equi join conditions provided(If not provided use 0=0) and check for filter while iterating for equi join condition matched rows in com.facebook.presto.operator.LookupJoinOperator.joinCurrentPosition() method.I want to commit this.Please tell regarding acceptance of patch for this. @martint Can you discuss any other approach to do so.Thank you everyone.

**Comment by yuananf** [comment]
Great job! 
I think you can make a pull request for this and discuss about it.

**Comment by cberner** [comment]
@dilipkasana great! Yes, the best way would be to make a pull request, so we can look at the code and review it

**Comment by cberner** [comment]
I think @joy-yao is working on cross join support that should help with this

**Comment by dilipkasana** [comment]
Is it resolved or planned or will be plan later.

**Comment by sunchao** [comment]
Just asking: what is the status for this issue? Is there a PR we can look at? cc @dilipkasana @cberner

**Comment by KBP-TDC** [comment]
Any chance you can try the latest Presto (0.151 at this point) and verify whether there is anything missing? We have non-equi joins working now I believe thanks to @losipiuk 
Please refer to Presto docs at https://prestodb.io/docs/current/sql/select.html

**Comment by losipiuk** [comment]
Just take in mind that performance is not optimal for some classes of queries. There is pending PR which improves that a lot (https://github.com/prestodb/presto/pull/5810).

**Comment by sunchao** [comment]
Thanks @KBP-TDC and @losipiuk - didn't realize this work is already done. :)
I'll upgrade my Presto version and have a try. Will watch for the improvement.
