### ISSUE TITLE
Dose Presto have the plan to implement cache hierarchy?

### ISSUE THREAD

**Issue by lvxin1986** [facebook/presto#2084]
Hello:
Presto team.
We found one problem in the course of using the presto is that: presto has  no cache.
 We have ran a query on presto,But if we rerun the same query on presto, it will  re-read the data from the data source and re-compute the intermediate data.
This performance will be very low if do not use cache.Whether Presto have the plan to implement  cache hierarchy?

**Comment by cberner** [comment]
Yes, there's some initial support for this here: https://github.com/facebook/presto/pull/2645

**Comment by dborkar** [comment]
Depending on the underlying storage engine you are using, Alluxio might be an option for presto caching. For S3, HDFS, and S3-compatible object stores, Alluxio caches both metadata and data. Typically you would co-locate the presto worker and the alluxio worker on the same instance, vm or container. this will allow for tightest locality. here are some tips: https://www.alluxio.io/blog/top-5-performance-tuning-tips-for-running-presto-on-alluxio-1/.
