### ISSUE TITLE
Add CREATE TABLE IF NOT EXISTS

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2108]
Add the optional `IF NOT EXISTS` syntax for `CREATE TABLE`:

    CREATE TABLE [IF NOT EXISTS] name AS ...

**Comment by joy-yao** [comment]
Claiming this task.

**Comment by joy-yao** [comment]
Code needs to be cleaned up before working on this task. Returning this task.

**Comment by yuananf** [comment]
@joy-yao , have you finish this one?

**Comment by joy-yao** [comment]
@yuananf , I am not working on it.

**Comment by cawallin** [comment]
Fixed with #3090, can be closed. @electrum

**Comment by cberner** [comment]
Thanks @cawallin!
