### ISSUE TITLE
Cannot cast JSON to MAP

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2109]
SELECT CAST(CAST('{"foo":"bar"}' AS json) AS map<varchar, varchar>);

**Comment by radsimu** [comment]
CAST('{"foo":"bar"}' AS json) would result in a json string type which cannot be cast to map, but only to varchar. This should have been:

    SELECT CAST(JSON '{"foo":"bar"}' AS map<varchar, varchar>);

or

    SELECT CAST(json_parse('{"foo":"bar"}') AS map<varchar, varchar>);

**Comment by dengjack** [comment]
map<varchar, json>
