### ISSUE TITLE
Quoted special functions don't resolve correctly

### ISSUE THREAD

**Issue by martint** [facebook/presto#2111]
This works:

```
presto:di> select current_timestamp;
                    _col0                    
---------------------------------------------
 2014-12-12 17:59:18.737 America/Los_Angeles 
(1 row)
```

But this does not:

```
presto:di> select "current_timestamp" ;
Query 20141213_015319_01754_8t988 failed: Column 'current_timestamp' cannot be resolved
```

The same applies to current_date and current_time.

**Comment by angoenka** [comment]
Working on this one.

**Comment by angoenka** [comment]
sure. will wait for it.

**Comment by electrum** [comment]
We came to the conclusion that the current behavior is actually correct: they are only special functions in the non-quoted form. When quoted, they should be treated as an identifier.
