### ISSUE TITLE
Why i can't build the project for eclipse?

### ISSUE THREAD

**Issue by aslldab1** [facebook/presto#2115]
I build the project with mvn eclipse:eclipse, but failed with checkstyle violation. After set the property </air.check.fail-checkstyle> to false, another error occured:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.9:analyze-only (default) on project presto-client: Cannot analyze dependencies: /media/WorkSpace/presto/presto0.88/presto-spi/target/classes (is a folder) -> [Help 1]

**Comment by electrum** [comment]
Please re-open if you are still having trouble running Presto in Eclipse. Thanks!
