### ISSUE TITLE
Support for min and max aggregate functions on date types

### ISSUE THREAD

**Issue by surjikal** [facebook/presto#2170]
This is crucial for the reports I'm making. Postgres supports this. I was looking at the source and it seems like it wouldn't be too difficult to implement, so I may send a pull request sometime soon.

Example use case:

I have an events table, where each event has a timestamp. I want to know the time span of events:

```sql
select
  min(timestamp) as min_ts
, max(timestamp) as max_ts
from events;
```

This is super useful to make a time select widget in a UI.

**Comment by surjikal** [comment]
Workaround suggested by @electrum :

```sql
select
  from_unixtime(min(to_unixtime(timestamp))) as min_ts
, from_unixtime(max(to_unixtime(timestamp))) as max_ts
from events
```

**Comment by cberner** [comment]
This should be fixed now
