### ISSUE TITLE
Invalid filter node is produced when casting constant values into DOUBLE within where clause

### ISSUE THREAD

**Issue by xerial** [facebook/presto#2193]
With presto-0.88, the following query produces an incorrect filter plan:
```
presto:default> explain SELECT * FROM (VALUES(1000)) t(a) where a * 0.1 > 1.0;
                     Query Plan
-----------------------------------------------------
 - Output[a]
         a := field
     - Filter[(("field" * 0) > 1)] => [field:bigint]
         - Values => [field:bigint]
                 1000
```
The constant 0.1 (and 1.0) is truncated to 0 (and 1) in the filter condition.

If the double value is referenced from a column, it produces the correct plan:
```
presto:default> explain SELECT * FROM (VALUES(1000, 0.1)) t(a, b) where a * b > 1.0;
                                          Query Plan
-----------------------------------------------------------------------------------------------
 - Output[a, b]
         a := field
         b := field_0
     - Filter[((CAST("field" AS DOUBLE) * "field_0") > 1.0)] => [field:bigint, field_0:double]
         - Values => [field:bigint, field_0:double]
                 1000, 0.1
```

**Comment by martint** [comment]
This seems to work fine in 0.89:

```
presto> explain SELECT * FROM (VALUES(1000)) t(a) where a * 0.1 > 1.0;
                               Query Plan                                
-------------------------------------------------------------------------
 - Output[a]                                                             
         a := field                                                      
     - Filter[((CAST("field" AS DOUBLE) * 0.1) > 1.0)] => [field:bigint] 
         - Values => [field:bigint]                                      
                 (1000)                                                  
                                                                         
(1 row)
```

I'm not sure which commit introduced the problem and which one fixed it, though. I'll try to track it down later to understand what happened.

**Comment by xerial** [comment]
Thanks. I'll try 0.89

**Comment by xerial** [comment]
This problem might be related to the query plan optimizer implemented in our connector.

Sorry for bothering, but knowing 0.89 has no problem is enough for now. Thanks.

**Comment by frsyuki** [comment]
Note: An optimizer we implemented analyzes WHERE conditions and evaluates deterministic functions including our custom UDFs. For example, we have a function called `TD_TIME_RANGE(time int, start_time VARCHAR, end_time VARCHAR)`. The optimizer converts the function call to "start_time_in_unix_time <= time AND time < end_time_in_unix_time` so that connector plugin can get pushdown-ed condition.
