### ISSUE TITLE
Critical Bug : [Queries Returning Wrong Results]While writing Slice bytes (Queries operating on Varchar/VarBinary/Slice will produce wrong result, If their binary Representation is not UTF-8 compatible)

### ISSUE THREAD

**Issue by dilipkasana** [facebook/presto#2197]
Reproduce the Bug Steps:
1.Run the following queries
   A.presto:default>        select length(from_base64('gw==')) as len;
   len
     1
(1 row)

B. presto:default>      select length(haha) as len from (select from_base64('gw==') as haha);
 
   len
     3
(1 row)

Here Same query giving different result.Critical bug If one is storing UTF-8 Incompatible bytes,For example here from_base64('gw==') = {-125} in byte representation.

**Comment by dain** [comment]
If you explain the two queries, they both result in constant plans, so I think this is a bug in the constant folder.
