### ISSUE TITLE
Array subscript operator fails for array[null][null]

### ISSUE THREAD

**Issue by nezihyigitbasi** [facebook/presto#2201]
While ``array[null]`` and ``array[1,2,3][null]`` are valid operations, ``array[null][null]`` fails. The ``ArraySubscriptOperator`` does a check in the ``specialize()`` method to ensure that it receives exactly one type, but for ``array[null][null]`` the type map is empty and the check fails. I removed the check and ran the existing unit tests (+ a new test for this case) and all work fine, but I also want to check with you to see whether that check is really necessary. 

Another issue that confused me is, it seems like ``null`` is a valid subscript and while evaluating ``array[1,2,3][null]`` the ``ExpressionInterpreter`` takes a shortcut [here](https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/planner/ExpressionInterpreter.java#L784) and returns ``null``. But, [here](https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/metadata/OperatorType.java#L160) the ``OperatorType`` class says that the subscript has to be a ``bigint`` (and this validation is called in ``FunctionRegistry.operatorInfo()``, which is **not** called by the array and map subscript operators so probably this code is never called at all for the subscript operators). Seemed conflicting to me.

```
presto:default> select array[null];
 _col0  
--------
 [null] 
(1 row)
```
```
presto:default> select array[1,2,3][null];
 _col0 
-------
 NULL  
(1 row)
```

```
presto:default> select array[null][null];
Query 20150108_213125_00001_nig3u failed: Expected one type, got {}
java.lang.IllegalArgumentException: Expected one type, got {}
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at com.facebook.presto.operator.scalar.ArraySubscriptOperator.specialize(ArraySubscriptOperator.java:100)
```

**Comment by cberner** [comment]
Yes, you need that check because the type in that type map is used to determine the return type of the function. So the bug here is that the map is empty. "select array[null][null]" should work and it should result in a NULL value of UnknownType type

**Comment by nezihyigitbasi** [comment]
The thing is for ``ARRAY[NULL][1]`` the type map contains ``unknown`` type. But, for ``ARRAY[NULL][NULL]`` the type map is empty. What's the reason for that?

**Comment by cberner** [comment]
That's a bug. It should be `unknown` in both cases

**Comment by nezihyigitbasi** [comment]
This bug seems to be fixed in the latest master.
