### ISSUE TITLE
JSON functions need categorized errors

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2212]
This is one example, but there might be others. The unit tests need to include negative tests as well. See `assertInvalidFunction` in `TestStringFunctions`.

```
presto> select json_extract_scalar('', '');
...
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0

**Comment by nezihyigitbasi** [comment]
taking a look at this one

**Comment by nezihyigitbasi** [comment]
@electrum just created a PR that addresses both this issue and #2211, which is closely related.
