### ISSUE TITLE
Bug: PrestoDB get the wrong result with round(x, d)  function

### ISSUE THREAD

**Issue by lvxin1986** [facebook/presto#2223]
I'm using funtion:round(x, d) ,but i found that :maybe this funtion has a bug like the follows:
presto:default> select round(24.700000000000003,14);
       _col0       
-------------------
 24.70000000000001 
(1 row)

Is it a bug?

**Comment by lvxin1986** [comment]
maybe we should use BigDecimal:
 double num=24.700000000000003;
        int decimals = 14;
        System.out.println("num = "+num);
        System.out.println("new BigDecimal(num).round(new MathContext(16)) = "+new BigDecimal(num).round(new MathContext(16)));
        double factor = Math.pow(10, decimals);
        System.out.println("factor = "+factor);
        System.out.println("num * factor =" +num * factor);
        System.out.println("num * factor + 0.5 =" +(num * factor + 0.5));
        System.out.println("Math.floor(num * factor + 0.5) = " + Math.floor(num * factor + 0.5));
        System.out.println("Math.floor(num * factor + 0.5) / factor = "+Math.floor(num * factor + 0.5) / factor);
-------------------------------------------------------------------------------------------------------
num = 24.700000000000003
new BigDecimal(num).round(new MathContext(16)) = 24.70000000000000
factor = 1.0E14
num * factor =2.4700000000000005E15
num * factor + 0.5 =2.470000000000001E15
Math.floor(num * factor + 0.5) = 2.470000000000001E15
Math.floor(num * factor + 0.5) / factor = 24.70000000000001

**Comment by cberner** [comment]
https://github.com/facebook/presto/pull/2227
