### ISSUE TITLE
presto 0.89 compile phase dependency analyze error

### ISSUE THREAD

**Issue by yitzchakl** [facebook/presto#2247]
Hi All.

When i'm trying to run maven compile on version 0.89 i'm getting errors on module presto-client that cannot analyze presto-spi dependency jar (part of maven dependency plugin analyze only phase), it also happens on module presto-tpch, my workaround was to skip running the plugin when compiling presto-client.

my maven command was : mvn -DskipTests clean compile
i'm running the build on linux 2.6.32-431.20.3.el6.x86_64 with jdk1.8.0_25 and maven 3.2.3

Thanks!
Yitzchak.

**Comment by dain** [comment]
I believe for the build to complete, you need to run the install phase.  For example, `mvn -DskipTests clean install`.

If that doesn't work, please reopen this issue.
