### ISSUE TITLE
Add support for hash-partitioned semijoins

### ISSUE THREAD

**Issue by martint** [facebook/presto#2263]
Semijoin queries (see example below) currently execute using broadcast strategy even if distributed joins are enabled.

```sql
SELECT * 
FROM T 
WHERE a IN (SELECT b FROM U)
```

See https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddExchanges.java#L338

**Comment by cberner** [comment]
@martint did you implement this already?

**Comment by haozhun** [comment]
@martint Rebased. But I have a few questions for this.
