### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by nguyengiangdev** [facebook/presto#2264]
Hi presto team!

I have installed both java 6 and java 7, but i switch java 7 and then run ./presto --server localhost:8080, it have errors: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/facebook/presto/cli/Presto : Unsupported major.minor version 52.0. I switch to java 6, it same error, every can fix that

**Comment by dain** [comment]
Presto requires Java 8

**Comment by nguyengiangdev** [comment]
@dain ok i will try.
