### ISSUE TITLE
Add optimizer for LIMIT 0

### ISSUE THREAD

**Issue by dain** [facebook/presto#2283]
Currently, the plan a query with `LIMIT 0` includes all nodes under the limit.  This causes Presto to start scheduling the query and then tear down the query.  Instead, the plan nodes under a `LIMIT 0` node should be replaced with an empty `VALUES` node, which will cause the query to complete instantly.

**Comment by zhenxiao** [comment]
May I claim this one?

**Comment by dain** [comment]
Sure

**Comment by martint** [comment]
Fixed
