### ISSUE TITLE
Allow ValuesNode with 0 rows

### ISSUE THREAD

**Issue by martint** [facebook/presto#2291]
Once this is fixed, update LimitPushdown to create an empty ValuesNode instead of a Limit(0) on top of a single-row ValuesNode.

**Comment by zhenxiao** [comment]
Let me try it

**Comment by zhenxiao** [comment]
@martint this will release the non-empty page constraint in PageSplitterUtil.java:
line 29 checkArgument(page.getPositionCount() > 0, "page is empty");
Do you think this would trigger memory problem?

**Comment by zhenxiao** [comment]
@martint ignore my last comment. Update ValuesOperator only
