### ISSUE TITLE
Query 20150129_032824_00012_rhk3t, STARTING, 0 nodes, 0 splits, Why?

### ISSUE THREAD

**Issue by haolujun** [facebook/presto#2294]
I have made a presto cluster wtih 25 nodes(machines). I found a very strange issue.
when I run a Query like:  select count(1) as pv, inter_name from hive_yz.acorn_3g.mcs_access where log_date = '2015-01-27' group by inter_name order by pv desc limit 10;

First time, 10 querys run at the same time and only 2 querys got rigth answer, 2 querys got crashed, 6 querys got the right answer but made my terminator no response。

So I know, because the resources are not enough to meet the 10 querys running at the same time.

Then, I decided to try 5 querys at the same time, but this time I got the strange message like this:
Query 20150129_032824_00012_rhk3t, STARTING, 0 nodes, 0 splits
Query 20150129_032824_00012_rhk3t failed: java.lang.Exception: java.util.concurrent.TimeoutException: Timeout waiting for task.

And now, there is no query can work. So I guess there is something makes my cluster out of work. I don't know  why and how to solve it.

**Comment by cberner** [comment]
There were a bunch of communication bugs fixed in the last few release. Please re-open, if this is still an issue
