### ISSUE TITLE
How to use semijoin for query?

### ISSUE THREAD

**Issue by aslldab1** [facebook/presto#2314]
I search the code and found the SemiJoinNode. In which case will presto use semijoin? Please give me a specific scenarios or examples.
Thanks!

**Comment by erichwang** [comment]
semijoins are used when you do an IN clause with a subquery instead of a static list of values. For example:

SELECT * FROM TABLE t_1 WHERE col_x IN (SELECT col_y FROM t_2);

**Comment by aslldab1** [comment]
I see. Thanks so much!

**Comment by aslldab1** [comment]
What's the difference between semijoin and in query?

**Comment by dain** [comment]
The `IN` expression is part of the SQL language.  The a semi join is a technique we use in the Presto execution engine to evaluate the `IN` clause.

**Comment by aslldab1** [comment]
I construct a semijoin node with query like 'SELECT * FROM TABLE t_1 WHERE col_x IN (SELECT col_y FROM t_2);', but when I check log of postgresql, it executes select col_x from t_1 without the 'in' clause. Why not execute 'in' query?

**Comment by cberner** [comment]
There's no predicate push down of semi joins to the postgres connector

**Comment by wuwei0509** [comment]
how can I disable the semi join?
