### ISSUE TITLE
How to get the schemaName and tableName with a TableScanNode?

### ISSUE THREAD

**Issue by aslldab1** [facebook/presto#2319]
I've search the code for many times, or there is no way for this calling?

**Comment by dilipkasana** [comment]
You directly cannot get schemaName and tableName from TableScanNode.But  instances of ConnectorTableHandle may have this information based on your need.
TableScaneNode.getTableHandle().getConnectorHandle() will give an instance of ConnectorTableHandle.You can check and typecast this to your interested ConnectorTableHandle and retrieve tableName and schema name. To see how to set them see : com.facebook.presto.connector.informationSchema.InformationSchemaTableHandle.

**Comment by dilipkasana** [comment]
Or instead you can call Metadata.getTableMetadata(TableScaneNode.getTableHandle()).getTable().getSchemaName();
and
 Metadata.getTableMetadata(TableScaneNode.getTableHandle()).getTable().getTableName();

**Comment by aslldab1** [comment]
Thanks so much! The last answer perfectly meet my need.
