### ISSUE TITLE
Query stuck several time : frequency (1/3 to 1/5)

### ISSUE THREAD

**Issue by dilipkasana** [facebook/presto#2320]
Presto-Server Version for issue creation 0.82/0.86.Not tested on master/0.92.
Catalog : tpch,schema : tiny
Steps for recreating issue : 
1.Use catalog tpch;Use schema tiny;
2.Run several time below given query:
select * from ((select 20 as id) left join (select * from customer order by custkey limit 1) on 1=1);
Run query several times and query will stuck.(expected 1 times in 5 runs).

Below is how it is shown on cli:
presto:tiny> select * from ((select 20 as id) left join (select * from customer order by custkey limit 1) on 1=1);
 id | custkey |        name        |      address      | nationkey |      phone      | acctbal | mktsegment |                            comment                         
----+---------+--------------------+-------------------+-----------+-----------------+---------+------------+------------------------------------------------------------
 20 |       1 | Customer#000000001 | IVhzIApeRb ot,c,E |        15 | 25-989-741-2988 |  711.56 | BUILDING   | to the even, regular platelets. regular, ironic epitaphs na
(1 row)

Query 20150204_093956_00003_uf25v, FINISHED, 1 node
http://localhost:8180/v1/query/20150204_093956_00003_uf25v?pretty
Splits: 6 total, 6 done (100.00%)
CPU Time: 0.1s total, 26.8K rows/s,     0B/s, 83% active
Per Node: 0.0 parallelism, 1.33K rows/s,     0B/s
Parallelism: 0.0
0:01 [1.5K rows, 0B] [1.33K rows/s, 0B/s]

presto:tiny> select * from ((select 20 as id) left join (select * from customer order by custkey limit 1) on 1=1);

Query 20150204_093958_00004_uf25v, RUNNING, 1 node, 6 splits
http://localhost:8180/v1/query/20150204_093958_00004_uf25v?pretty
Splits:   0 queued, 2 running, 4 done
CPU Time: 0.1s total, 19.5K rows/s,     0B/s, 12% active
Per Node: 0.0 parallelism,     5 rows/s,     0B/s
Parallelism: 0.0
4:53 [ 1.5K rows,     0B] [    5 rows/s,     0B/s] [============================>>>>>>>>>>>>>>] 66%

     STAGES   ROWS  ROWS/s  BYTES  BYTES/s  QUEUED    RUN   DONE
0.........R      5       0  1.67K       5B       0      2      0
  1.......F   1.5K       0     0B       0B       0      0      4

**Comment by cberner** [comment]
We fixed lots of communication bugs in recent release. Please re-open, if you still see this issue.
