### ISSUE TITLE
Detect quick worker restarts and fail queries immediately

### ISSUE THREAD

**Issue by dain** [facebook/presto#2330]
When a worker restart, the engine may not notice the change and wait for work that will never complete.  An easy fix for this is to add the node instance id to task info and then the `HttpRemoteTask` would see the change and fail the task.

This issue is identified by having a task stuck in the RUNNING state with 0 splits assigned.  If there are multiple queries, they will all be stuck on the same node or nodes that rebooted.

**Comment by xerial** [comment]
Thanks for filing this issue.

**Comment by kzk** [comment]
:+1:
