### ISSUE TITLE
How the datas get joined?

### ISSUE THREAD

**Issue by aslldab1** [facebook/presto#2349]
After fetching data from nodes, presto need to join the data with join method like `sort merge join`. How much join method do presto support and how to choose join methods? Is there any documents about this question?

**Comment by cberner** [comment]
Presto supports hash join in two different ways. In the first, one table is broadcast to all workers and the second table is streamed, and in the other (enabled via the `distributed-joins-enabled=true` flag) the first table is hash distributed to the workers, and then the second table is streamed using the same hash function

**Comment by aslldab1** [comment]
What does `steamed` means?

**Comment by aslldab1** [comment]
I want to use cost model to estimate cost of join operation in presto.

**Comment by jangorecki** [comment]
There is some info in [admin/tuning](https://prestodb.io/docs/current/admin/tuning.html), quite few, no examples.

**Comment by KBP-TDC** [comment]
@aslldab1 @jangorecki   I would look at the output of EXPLAIN, EXPLAIN (TYPE DISTRUBUTED), and EXPLAIN ANALYZE. Presto UI also has a nice visual query plan with runtime metrics updated as query is in progress. That should help to understand the performance.
Btw. this doc is slightly more detailed: http://teradata.github.io/presto/docs/148t/admin/tuning.html
