### ISSUE TITLE
Code Results in Wrong Expression : And so on Query Result wrong 

### ISSUE THREAD

**Issue by dilipkasana** [facebook/presto#2350]
package com.facebook.presto.sql.planner
class DomainTranslator
method : normalizeSimpleComparison(ComparisonExpression comparison) ::ComparisonExpression
calls 
method : flipComparisonDirection(ComparisonExpression.Type type):ComparisonExpression.Type

assumes that The remaining types have no direction association.But when someone defines operator that has direction association like (in case of ranges in postgres: http://www.postgresql.org/docs/9.2/static/functions-range.html) operator like left_contains_right have direction assocation.

When someone defines this kind of operators it flips the node's right and left values if left is literal  but not operator type and results in wrong query outputs.

We should not predict  association direction of ComparisonExpression.Lets the opearator defines it and should instead asks the operator in some way about it or instead throw an exception for now.

**Comment by electrum** [comment]
Currently, `DomainTranslator` and `TupleDomain` only support a limited number of built-in types. We only recently extended/hacked it to support `date` and `timestamp` types. These will have to be rewritten to support arbitrary types.

**Comment by electrum** [comment]
Were you able to produce the wrong results by adding a custom type that has direction association?

**Comment by dilipkasana** [comment]
Hi David,
    Not able to produce any wrong results because query fails later in
type-checking and some time in creating comparisonExpression.

 I have added new Operator that has direction association.and it fails but
it can work if isSimpleComparison(node) would have returned true in that
case.
      1.define an operator say LEFT_CONTAINS_RIGHT  (symbol : @> )
      2. Run query like : select id1 from range where id1 @> 1000; (type of
id1 : bigint)

      returns : Query 20150212_080242_00017_qb8kc failed: Unhandled type:
LEFT_CONTAINS_RIGHT

      3. presto:default> select count(*) from test_range_gist where ir @>
int4range(10,10);

          _col0

            ------

            6200

         (1 row)

       4. presto:default> select count(*) from test_range_gist where ir @>
10;   (type of ir is int4range , it is custom)

            Query 20150212_080818_00019_qb8kc failed: Value 10 is not of
expected type int4range

            java.lang.IllegalStateException: Value 10 is not of expected
type int4range


Conclusion : instead of throwing any exception isSimpleComparison(node)
should return false in above cases and let the query to be run.

On Thu, Feb 12, 2015 at 1:46 AM, David Phillips <notifications@github.com>
wrote:

> Were you able to produce the wrong results by adding a custom type that
> has direction association?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/presto/issues/2350#issuecomment-73955965>.
>



-- 
*--*
*Thanks and Regards,*

*Dilip Singh Kasana*

Software Developer, RnD

*DRISHTI-SOFT SOLUTIONS PVT. LTD*

*NIT,Jaipur (2009-2013)*

 Ph :    +919958378173

**Comment by cberner** [comment]
I would suggest adding functions for these, instead of operators. We're not planning to introduce non-ANSI sql symbols at this time
