### ISSUE TITLE
Error in ImmutableCollectors.java after merge with 0.93 release

### ISSUE THREAD

**Issue by rxiadiya** [facebook/presto#2373]
I am seeing the Following error in ImmutableCollectors.java after merge with 0.93 release and updated to Java 1.8. 
Any ideas how to resolve it ? 

    public static <T> Collector<T, ?, ImmutableList<T>> toImmutableList()
    {
        return Collector.<T, ImmutableList.Builder<T>, ImmutableList<T>>of(
                ImmutableList.Builder::new,
                ImmutableList.Builder::add,
                (left, right) -> {
                    left.addAll(right.build());
                    return left;
                },
                ImmutableList.Builder::build);
    }

Line 29 of ImmutableCollectors.java
The constructed object of type ImmutableList.Builder is incompatible with the descriptor's return type: R

Line 30 of ImmutableCollectors.java
Cannot make a static reference to the non-static method add(Object[]) from the type ImmutableList.Builder

Line 35 of ImmutableCollectors.java
The target type of this expression must be a functional interface

Thanks

**Comment by dain** [comment]
Are these compile errors?  We have been successfully compiling this for a long time now.

**Comment by rxiadiya** [comment]
Got it , turns out my compiler were not configured correctly in Eclipse , now fixed . Thank you Dain.

**Comment by liguohuizmy** [comment]
Excuse me, can you tell me how to this problem solved. I encounter the same problem.
