### ISSUE TITLE
Ensure that all table writing is done partitioned

### ISSUE THREAD

**Issue by cberner** [facebook/presto#2400]

**Comment by cberner** [comment]
Assigning this to @haozhun

**Comment by damiencarol** [comment]
@cberner I don't understand the goal of this ticket. Do you mean you want to add an option to force partitioning when writing? Support partitioning in write operation?

**Comment by cberner** [comment]
Just to enforce that the write stage isn't running on a single machine. For queries like CREATE TABLE AS ... LIMIT 1000000 you end up doing the table write from a single node, because it happens after the LIMIT

**Comment by damiencarol** [comment]
ok, I get it. There are the same "LIMIT 1000000" problem in HIVE.
It's a good feature.

**Comment by cberner** [comment]
https://github.com/facebook/presto/pull/2462
