### ISSUE TITLE
Add dummy decimal type

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2417]
Hive supports a decimal type. Even though we don't yet have support for this in Presto, we would like users to at least be able to read it.

We should create a decimal type in Presto that only supports casting to varchar, bigint or double. For now, the type can probably be a copy of varchar. Creating the type now will allow users to read the data and process it in a forwards compatible way (that will continue to work when we implement it properly).

**Comment by cberner** [comment]
Superseded by: https://github.com/facebook/presto/issues/2797
