### ISSUE TITLE
Create approx_percentile function that returns multiple percentiles

### ISSUE THREAD

**Issue by martint** [facebook/presto#2452]
Currently, approx_percentile takes a single argument for the percentile to compute. Now that presto supports array types, we should consider adding a new version:
- `approx_percentile(value:double, quantiles:array<double>): array<double>`

Possibly, also add the following version that computes each quantile between 0.0 and 1.0 in steps of `granularity`. E.g., if `granularity` is 10, the function returns the quantiles 0, 10, 20, 30, ..., 100: 
- `approx_percentile(value:double, granularity:double): array<double>`
    

Alternatively, we could implement a "sequence" function that produces an array of values based on a range and step size and let users compose them as necessary (e.g., `approx_percentile(value, sequence(0.0, 1.0, 0.01)`)

**Comment by haozhun** [comment]
@raghavsethi is working on this.

**Comment by raghavsethi** [comment]
Merged #3595.

**Comment by bradhannigandaley** [comment]
This appears to work for `bigint` fields but not for `double`s. e.g. I have a `double` field called `height`, and the query `SELECT approx_percentile(height, ARRAY[0.25,0.5,0.75])` results in the following error:

```Unexpected parameters (double, array<double>) for function approx_percentile. Expected: approx_percentile(bigint, double) , approx_percentile(bigint, bigint, double, double) , approx_percentile(bigint, bigint, double) , approx_percentile(bigint, array<double>) , approx_percentile(bigint, bigint, array<double>) , approx_percentile(double, double) , approx_percentile(double, bigint, double, double) , approx_percentile(double, bigint, double)```

But it does produce something if I cast `height` to `bigint`.

**Comment by raghavsethi** [comment]
Hmm I can repro this. Taking a look now. Tracking in #4395.

**Comment by MichaelChirico** [comment]
Chiming in here that the documentation should reflect the expected input type for `percentages`:

https://prestodb.io/docs/current/functions/aggregate.html
