### ISSUE TITLE
MAP type is not comparable

### ISSUE THREAD

**Issue by cberner** [facebook/presto#2454]
MapType is not comparable even though there is an = and != operator defined

**Comment by zhenxiao** [comment]
@cberner @martint do we have a description like:
https://github.com/facebook/presto/issues/1816

**Comment by martint** [comment]
Maps are *almost* comparable (they implement the = and != operator), but the isComparable method in MapType is currently implemented incorrectly. It should do something like ArrayType's isComparable, and return true if the value type is comparable.

**Comment by zhenxiao** [comment]
@martint thank you, get it. Let me take a try.
