### ISSUE TITLE
Why don't presto support join ordering optimization?

### ISSUE THREAD

**Issue by aslldab1** [facebook/presto#2471]
Join ordering optimization has been widely applied in rdbms, why don't presto optimize query plan with it?

**Comment by cberner** [comment]
We're planning to implement this, but first we need to add an API for connectors to supply stats to Presto, so that it can chose the appropriate join order

**Comment by yuananf** [comment]
@cberner is this on the todo list now?

**Comment by cberner** [comment]
It's on the *very* long term to do list. I don't think it will land any time soon. The issue is that we don't have any system for stats or cost based analysis, so it's a lot of work

**Comment by yuananf** [comment]
I see.
