### ISSUE TITLE
Refactor MaxBy to bind types in specialize()

### ISSUE THREAD

**Issue by cberner** [facebook/presto#2475]
MaxBy stores the key and value types in the MaxOrMinByState. Instead we should bind them into the input, combine, and output method handles during specialization. Similar to how it's done in `ArrayEqualOperator`

**Comment by haozhun** [comment]
`ArrayEqualOperator` is not an aggregation function. It can use `MethodHandle`. Implementation of aggregation function is required to use `Method` instead. And `bind` is not available for `Method`s.

**Comment by cberner** [comment]
Ya, we'll have to refactor the aggregation compilers to work with MethodHandle

**Comment by cberner** [comment]
I did the first step of this: https://github.com/facebook/presto/commit/23dd5aa5877885d795992c196e5776303955cfd8

**Comment by haozhun** [comment]
For the second step, doing it straightforwardly will require 16 different state types (long/long, long/double, long/slice, long/bool, double/long, ...) This does not feel like a viable option.
