### ISSUE TITLE
Coercion doesn't work for UNION

### ISSUE THREAD

**Issue by cberner** [facebook/presto#2532]
select * from (values (1)) union all (values (NULL));

fails with:

Query 20150316_192120_21072_kzg7u failed: column 0 in union query has incompatible types: bigint, unknown

**Comment by yaoxin226** [comment]
Hi @haozhun , are you working on this issue? Can I claim it?

**Comment by haozhun** [comment]
@yaoxin226 Sorry for the late reply. I'm working on it.

**Comment by haozhun** [comment]
@yaoxin226 You can take a look at the fix if you interested.

**Comment by yaoxin226** [comment]
thanks @haozhun , I will take look at it.
