### ISSUE TITLE
Implement array_to_string

### ISSUE THREAD

**Issue by cberner** [facebook/presto#2539]
We need a function similar to Postgres' `array_to_string` (http://www.postgresql.org/docs/9.1/static/functions-array.html)

@martint @electrum any preferences on the name?

**Comment by nezihyigitbasi** [comment]
@cberner want to claim this one if no one is looking at it.

**Comment by cberner** [comment]
No one that I know of :)

**Comment by nezihyigitbasi** [comment]
@electrum @martint  What do we want ``array_to_string([1,null,2], '-', null)`` to return? Is it ``1-null-2`` OR ``1--2``?

**Comment by nezihyigitbasi** [comment]
@cberner an initial version is ready for review.
