### ISSUE TITLE
Array comparison with null elements fails

### ISSUE THREAD

**Issue by nezihyigitbasi** [facebook/presto#2556]
Comparing two arrays where one of the arrays has a ``null`` element fails while formatting a proper error message. The root cause seems to be a ``%`` character added as a prefix to the internal operator names (see [this](https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/metadata/Signature.java#L195)), which is not properly escaped before calling the ``String.format()`` function. 

```
presto:default> select array[null] = array[22];
Query 20150318_202931_00000_k7d2p failed: Conversion = '$'
java.util.UnknownFormatConversionException: Conversion = '$'
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2555)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2927)
	at com.facebook.presto.sql.analyzer.SemanticException.<init>(SemanticException.java:28)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.coerceType(ExpressionAnalyzer.java:850)
```

This is the format string passed to ``String.format()`` (note the ``%$``):
```
Operator FunctionInfo{signature=%$operator$EQUAL(array<bigint>,array<bigint>):boolean, isAggregate=false, isWindow=false} argument 0 must evaluate to a %s (actual: %s)
```

I will be happy to fix this one after we determine a proper solution.  Does any other part of the code rely on the ``%`` prefix in the internal operator name?

**Comment by cawallin** [comment]
Fixed with #2625, which disallows comparisons with arrays with null elements

**Comment by cawallin** [comment]
@cberner can you close this please?

**Comment by cberner** [comment]
Yep, sorry about the delay been on vacation for the last week
