### ISSUE TITLE
Hive connector can return maps with null keys

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2563]
Null map keys are not supported in Presto and cannot be returned from the `StatementResource`.

**Comment by electrum** [comment]
This seems to be a regression in `MapBlockReader`: entries with null keys used to be discarded (this was lost in the memory representation change).

**Comment by dain** [comment]
This is not resolved.  Presto currently does not allow maps to contain null keys, so that would have to change first, and I don't think anyone is thinking about this right now.
