### ISSUE TITLE
use statement does not work in jdbc driver

### ISSUE THREAD

**Issue by ndsorrowchi** [facebook/presto#2578]
I tried "use catalog.tablename" query where catalog is "mysql1" and tablename is "test", but got an error telling me that use statement is not supported.

java.sql.SQLException: Query failed (#20150322_053610_00015_tur55): USE statement is not supported

**Comment by electrum** [comment]
Yes, it is only for the CLI. Use the standard setSchema and setCatalog methods on Connection.

Do you have a use case for supporting USE?
