### ISSUE TITLE
Specifier '%f' in Date Function is broken

### ISSUE THREAD

**Issue by hikoz** [facebook/presto#2590]
Specifier '%f' in Date Function acts as Milliseconds in date_parse,
Microseconds in date_format.
And not working properly in both way.

Written Microseconds in the Manual.
https://prestodb.io/docs/0.98/functions/datetime.html#mysql-date-functions

Implemented as Milliseconds with 6 digits in source code.
https://github.com/facebook/presto/blob/0.99/presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java#L879

```sql
> select date_format(TIMESTAMP '2015-03-04 05:06:07.8', '%s.%f');
 07.000800
; expects 07.800000

> select date_parse('1.1', '%s.%f');
 1970-01-01 00:00:01.001
; expects 1970-01-01 00:00:01.100000

> select date_parse('1.01', '%s.%f');
 1970-01-01 00:00:01.001
; expects 1970-01-01 00:00:01.010000

> select date_parse('1.1001', '%s.%f');
Query 20150325_073341_00262_4nhqg failed: Cannot parse "1.1001": Value 1001 for millisOfSecond must be in the range [0,999]
; expects 1970-01-01 00:00:01.100100
```

**Comment by haozhun** [comment]
Thank you for reporting. I believe there are some typo in the expected output you provided. I modified the expected output a bit. See if they look right to you.

    > select date_format(TIMESTAMP '2015-03-04 05:06:07.8', '%s.%f');
     07.000800
    ; expects 07.800000
    
    > select date_parse('1.1', '%s.%f');
     1970-01-01 00:00:01.001
    ; expects 1970-01-01 00:00:01.100
    
    > select date_parse('1.01', '%s.%f');
     1970-01-01 00:00:01.001
    ; expects 1970-01-01 00:00:01.010
    
    > select date_parse('1.1001', '%s.%f');
    Query 20150325_073341_00262_4nhqg failed: Cannot parse "1.1001": Value 1001 for millisOfSecond must be in the range [0,999]
    ; expects 1970-01-01 00:00:01.100

**Comment by hikoz** [comment]
Thank you for fixing it.
I tried to keep "Microsecond"(6 digits) in docs and backward compatibility.
Your expected output is preferable than I wrote.
But I really want is using "millisecond"(3 digits) in date_parse and date_format.
Output is like below.
```sql
> select date_format(TIMESTAMP '2015-03-04 05:06:07.8', '%s.%f');
 07.000800
; expects 07.800

> select date_parse('1.1', '%s.%f');
 1970-01-01 00:00:01.001
; expects 1970-01-01 00:00:01.100

> select date_parse('1.01', '%s.%f');
 1970-01-01 00:00:01.001
; expects 1970-01-01 00:00:01.010

> select date_parse('1.1001', '%s.%f');
Query 20150325_073341_00262_4nhqg failed: Cannot parse "1.1001": Value 1001 for millisOfSecond must be in the range [0,999]
; Query 20150325_xxxxx failed: Invalid format: "1.1001" is malformed at "1"
```

**Comment by electrum** [comment]
Use parse_datetime. The others are designed to be compatible with MySQL, so we can't change the format.

**Comment by electrum** [comment]
Actually, your example looks like a bug. I think that should be parsing as expected, with the microsecond portion being ignored.

**Comment by electrum** [comment]
Or is your example with the current code (not the code in the pull request)?

**Comment by haozhun** [comment]
The example is with the current code, not the one in the pull request.

**Comment by haozhun** [comment]
As @electrum said, this won't happen

    > select date_format(TIMESTAMP '2015-03-04 05:06:07.8', '%s.%f');
    ; expects 07.800

**Comment by hikoz** [comment]
OK. Thanks for the comments.

**Comment by hikoz** [comment]
Should I close now or after releasing 0.100?

**Comment by cberner** [comment]
You can close it, if the fix is in master
