### ISSUE TITLE
unnest with join stopped working

### ISSUE THREAD

**Issue by linehrr** [facebook/presto#2632]
unnest with join after used to work in Presto 0.86 and previous versions.
now we tried 0.97/0.98/0.99/0.100 and they all give syntax error.
```"Error evaluating constant expression: Constant expression cannot contain column references"```

in the release note, it does not mention about any backward incompatibility of unnest.
other queries that does not have unnest all works fine.
so we doubt that unnest might have been broken in the recent release.

example: (this following query works on 0.86 but not in the recent release)
```
schema:
pa:
history    array<string>

brand:
campaignID    string

---------------------------------------------------
presto:default> explain select
             ->                 split_part(bh.chunk, '-', 7) as campaignID,
             ->                 count(*)
             ->         from pa
             ->                 cross join unnest(history) AS bh (chunk)
             ->                 left outer join brand on (split_part(bh.chunk, '-', 7) = brand.campaignID)
             ->         where dt='2015-01-01'
             ->                 and split_part(bh.chunk, '-', 7) != '0'
             ->                 and brand.campaignID is null
             ->         group by split_part(bh.chunk, '-', 7);
Query 20150402_230734_00012_whxan failed: Error evaluating constant expression: Constant expression cannot contain column references
```

**Comment by haozhun** [comment]
Reproducible with a simpler query

    select a, b, c, d
    from (values (ARRAY [1]), (ARRAY[2, 3]), (ARRAY[0, 4, 5])) t(a)
    cross join unnest(a) u(b)
    left outer join (values (1, 'one'), (2, 'two'), (3, 'thr'), (4, 'fou'), (5, 'fiv'), (0, 'zer')) v(c, d)
        on b = c;

**Comment by haozhun** [comment]
The issue here is join precedence. For immediate workaround, please add a parenthesis around your cross join.

    select
            split_part(bh.chunk, '-', 7) as campaignID,
            count(*)
    from (pa cross join unnest(history) AS bh (chunk))
            left outer join brand on (split_part(bh.chunk, '-', 7) = brand.campaignID)
    where dt='2015-01-01'
            and split_part(bh.chunk, '-', 7) != '0'
            and brand.campaignID is null
    group by split_part(bh.chunk, '-', 7);

**Comment by linehrr** [comment]
thank you haozhun!
and also thanks for the quick work around.
however, our company has lots of queries written and deployed.
it's hard for us to make this hot fix everywhere.

hope we can fix this issue and push into the main branch ASAP and get this fixed in the next release.
we will still use 0.86 for now and will upgrade when this issue is fixed.

also we will try to create some regression test for Presto so we can catch this kind of issue faster and easier.

thanks,

Ryne

**Comment by haozhun** [comment]
Merged. Close

**Comment by electrum** [comment]
We run the Presto before every release on a sample of queries from the previous day. It runs against production and the candidate release. You might be able to have a similar setup with your own queries.

**Comment by linehrr** [comment]
yea I think it's a fantastic idea, I will do  the same setup as backward compatibility checks on new release pushing test.

**Comment by cberner** [comment]
We use the presto-verifier project, which might help you. There's some documentation here: https://prestodb.io/docs/current/installation/verifier.html

**Comment by linehrr** [comment]
thanks cberner, I will take a look :+1:
