### ISSUE TITLE
Server rufuse connection error after restarting

### ISSUE THREAD

**Issue by ndsorrowchi** [facebook/presto#2658]
Server refused connection: http://localhost:8080/v1/statement

I have a java server which has to add a new catalog and restart presto server to reload new catalogs. After restarting presto it has to run a create table as query.
I use Runtime.getRuntime.exec(command) to restart it and I put waitfor() there. Yet it doesn't work. I tried and found that it actually takes 8 seconds to be 'really' restarted. Any help with that?

**Comment by cberner** [comment]
Yes, there's extra latency starting up. I would run a query selecting from `system.runtime.nodes` and see if the cluster appears to be up
