### ISSUE TITLE
Reduce memory usage of map_agg

### ISSUE THREAD

**Issue by cberner** [facebook/presto#2662]
`map_agg` uses a very large amount of memory. We should write a new class (or modify the interface of `GroupByHash`) that's similar to `GroupByHash`, but operates on a single Block. Then replace `keysHash` in `KeyValuePairs` with that new class

**Comment by cawallin** [comment]
@cberner merged with PR #2825, can you close this issue?

**Comment by cberner** [comment]
Yep, thanks!
