### ISSUE TITLE
Username and/or password are incorrect

### ISSUE THREAD

**Issue by 0x4139** [facebook/presto#2668]
I have tried all versions from presto 0.80 to 0.100 i can't authenticate against a cassandra db  2.1.4 nor 2.0.14 . If i use no password everything works fine

my presto connector config is 

```
connector.name=cassandra
cassandra.contact-points=127.0.0.1
cassandra.username=cassandra
cassandra.password=cassandra

```

the error i get is 

```
presto:default> describe cassandra.system_auth.users;
Query 20150409_144516_00001_96dtc failed: Authentication error on host /127.0.0.1:9042: Username and/or password are incorrect
```

**Comment by electrum** [comment]
Remove the quotes in the properties file. Those are treated as literal quotes.

**Comment by 0x4139** [comment]
I removed them :), my code is the same as in the initial comment code block
...

**Comment by cberner** [comment]
Did that fix the issue for you?
