### ISSUE TITLE
Is there any document about raptor connector?

### ISSUE THREAD

**Issue by yuananf** [facebook/presto#2676]
I saw dain's ppt on presto-meetup last month, and it shows that raptor have been used in facebook.

I tested raptor connector with some tpch queries, and it was very very fast.

But I can't see any new document about raptor connector, the only information about raptor is in presto 0.69 release note, how can I config it with metadata in mysql?

**Comment by electrum** [comment]
We won't document it until it is ready for external use. We often do things like make backwards incompatible metadata changes that require complex manual steps to migrate. There will be more of these in the near feature as we add storage cleanup (physical storage is currently never reclaimed).

I'll look for MySQL instructions tomorrow.

**Comment by yuananf** [comment]
I see, thanks!

**Comment by electrum** [comment]
The MySQL support can be enabled by setting `metadata.db.type=mysql`, but the MySQL connection actually comes from Discovery, which requires creating a static announcement in Discovery (or having MySQL or another process announce into Discovery). Details in `MySqlDataSource` in Airlift.

We will simplify this before officially releasing Raptor. Supporting different databases for metadata, managing database migrations, etc. make things a lot more complicated.

**Comment by yuananf** [comment]
Thanks for explaining!
