### ISSUE TITLE
Rewrite Single Distinct having other aggregations into GroupBy

### ISSUE THREAD

**Issue by zhenxiao** [facebook/presto#2678]
https://github.com/facebook/presto/pull/2085 rewrite Single Distinct without other aggregations into GroupBy, follow the discussion, we could do the following:

SELECT store_code, 
       date_key, 
       Sum(sale_net_val) Sales_value, 
       Sum(sale_tot_qty) Qty, 
       Count(DISTINCT customer_code) 
FROM   sales 
GROUP  BY store_code, 
          date_key; 

be converted into:

SELECT store_code, 
       date_key, 
       Sum(s1)  Sales_value, 
       Sum(s2)  Qty, 
       Count(*) AS c 
FROM   (SELECT store_code, 
               date_key, 
               customer_code, 
               Sum(sale_net_val) AS s1, 
               Sum(sale_tot_qty) AS s2 
        FROM   sales 
        GROUP  BY s.store_code, 
                  date_key, 
                  customer_code) t1 
GROUP  BY store_code, 
          date_key

**Comment by stagraqubole** [comment]
Hi @cberner, is this closed because it will be taken care of as part of some other work or is it off the radar for now?

**Comment by cberner** [comment]
It was already fixed in https://github.com/prestodb/presto/pull/2085

**Comment by stagraqubole** [comment]
It did not cover the case this issue talks about ie splitting aggregations accompanying count distinct into two stage aggregations. I dont see that in code too, @zhenxiao please correct me if I am wrong

**Comment by zhenxiao** [comment]
@stagraqubole @cberner Seems this case is not covered. Shall we continue with it?

**Comment by stagraqubole** [comment]
We have seen a requirement of this, we can pick this up.

**Comment by stagraqubole** [comment]
Following the existing logic, queries will convert from
```
select sum(a), count(distinct b)
```
to
```
select sum(s), count(b) from (select sum(a) as s, b from T group by b)
```


But this wont work for functions like avg
```
select avg(a), count(distinct b)
```
to
```
select avg(s), count(b) from (select avg(a) as s, b from T group by b)
```

Supporting this would require adding ability in AggregationOperators to handle some aggregations in Intermedite state and some in partial state in same operator.

Instead, following this kind of converion (inspired by sparkSQL plan):
```
select sum(a), count(distinct b)
```
to
```
select first_not_null(if(group=0, a, null)), count(if(g=1, b, null))
from
  (select sum(A)
    (select expand({a, null, 0}, {null, b, 1}) as (A, B, group) from T)
  group by B, group
  )
```

This does require implementing new Operator `Expand` but this approach can be extended to handle multiple distincts as well.
First implementation shows 2x improvement over original query.
I will open a PR soon, added the context here for feedback/suggestions.
