### ISSUE TITLE
No FileSystem for scheme: s3a

### ISSUE THREAD

**Issue by soulmachine** [facebook/presto#2681]
It seems that Presto doesn't support the `s3a` schema.

I created an external table on Amazon S3 and used the location "s3a://xxx", then I could run all kinds of queries based on this table in Hive, but none of them could run in Presto, all returned the following error message:

    Query 20150413_000647_00004_pnfam failed: No FileSystem for scheme: s3a

According to the Hadoop official document, [Hadoop Wiki Amazon S3](https://wiki.apache.org/hadoop/AmazonS3), S3A is a successor to the S3 Native, s3n.

So is there any plan  to support `s3a` filesystem?

**Comment by zhenxiao** [comment]
@soulmachine no support for s3a yet. s3 and s3n are supported. We do not have s3a use case yet. Maybe I could simply patch and send you a PR to try?

**Comment by zhenxiao** [comment]
@soulmachine I take a try at https://github.com/facebook/presto/pull/2682, maybe you could try building Presto with my PR and see whether it is working. Your comments and suggestions are appreciated.

**Comment by electrum** [comment]
I just merged @zhenxiao's patch, so this will be supported in the next release. Thanks for letting us know about this.

You might also be able to make this work with the current release by adding `hive.config.resource=/path/to/config.xml` to your Hive catalog properties file where `config.xml` contains the following:
```xml
<?xml version="1.0"?>
<configuration>
<property>
    <name>fs.s3a.impl</name>
    <value>com.facebook.presto.hive.PrestoS3FileSystem</value>
</property>
</configuration>
```

**Comment by soulmachine** [comment]
Thanks @zhenxiao @electrum !

**Comment by pandeyp** [comment]
@soulmachine, I am trying to create an external table on Amazon EMR AMI Version (3.7.0) that uses Hadoop 2.4.0 and Hive 0.13.1 using Amazon S3 bucket and s3a scheme. But I am getting error below:-

<code>
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:Got exception: java.io.IOException No FileSystem for scheme: s3a)
</code>

Can you please enlighten me on how you were able to create external table using s3a scheme? Did you use the current versions available in Amazon AMI?
