### ISSUE TITLE
Presto create table with bad table name

### ISSUE THREAD

**Issue by ndsorrowchi** [facebook/presto#2722]
I tried to create a table through presto jdbc and got this tablename instad of 'copytest':
tmp_presto_d1df63756ab74e50995e524baef46d2d.

It worked correctly on my virtual machine yet has this problem on a real Amazon AWS server.

**Comment by electrum** [comment]
When you run a `CREATE TABLE ... AS ...` with the JDBC connector, it creates a temporary table with a random name like the one you see, then INSERTs the data into it, and finally renames the temporary table to the final name that you chose. I don't think we cleanup temporary tables yet if the query fails, so for now you will need to DROP them manually.

I filed #2754 for cleanup of temporary tables.
