### ISSUE TITLE
Implement partial JSON cast

### ISSUE THREAD

**Issue by cberner** [facebook/presto#2756]
`SELECT CAST('{"a": 1, "b": [2, 3]}' AS MAP<VARCHAR, JSON>)` should work

**Comment by Myrthan** [comment]
I'm claiming this one:)

**Comment by Myrthan** [comment]
In this particular case we want to pick "1" as JSON? 
'{"a": 1, "b": [2, 3]}' 
We are extracting from that VARCHAR which we supposed is properly JSON  keys. For every keys we arranged VARCHAR not JSON I think? Should this be changed to:
SELECT CAST('{"a": 1, "b": [2, 3]}' AS MAP<VARCHAR, VARCHAR>) ?
Query like this is working:
SELECT CAST(CAST('{"foo":"bar", "foo2":"foo3"}' AS json) AS map<varchar, varchar>);
I'm not sure what we want to achieve in this example. After read referenced issuse discussion I think it should change to MAP<VARCHAR, VARCHAR>.

**Comment by cberner** [comment]
After the cast. Lets assume the column is named "my_map". You should be able to do the following:
```
SELECT json_extract_scalar(my_map['a'], '$') => '1'
```
and
```
SELECT json_extract_scalar(my_map['b'], '$[0]') => '2'
```
