### ISSUE TITLE
Inconsistent plan for kafka connector

### ISSUE THREAD

**Issue by yuananf** [facebook/presto#2776]
I tested presto kafka connector and find a problem:

I can see the kafka topics in presto, but sometimes query on the table returns nothing, for example

Here are the results of the same query:
presto:s1> select count(*) from t2;
 _col0 
-------
  5503 
(1 row)

presto:s1> select count(*) from t2;
 _col0 
-------
     0 
(1 row)

I was quite confused about this, and I tried to explain this query
Why they have two different plan? Where is the Filter[false] come from?

presto:s1> explain select count(*) from t2;
                                                                                             Query Plan                                                                                             
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[_col0] => [count:bigint]                                                                                                                                                                  
         _col0 := count                                                                                                                                                                             
     - Aggregate(FINAL) => [count:bigint]                                                                                                                                                           
             count := "count"("count_3")                                                                                                                                                            
         - Exchange[GATHER] => count_3:bigint                                                                                                                                                       
             - Aggregate(PARTIAL) => [count_3:bigint]                                                                                                                                               
                     count_3 := "count"(*)                                                                                                                                                          
                 - TableScan[kafka:KafkaTableHandle{connectorId=kafka, schemaName=s1, tableName=t2, topicName=s1.t2, keyDataFormat=dummy, messageDataFormat=dummy}, original constraint=true] => [] 
                                                                                                                                                                                                    
(1 row)

presto:s1> explain select count(*) from t2;
                                                                                               Query Plan                                                                                               
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[_col0] => [count:bigint]                                                                                                                                                                      
         _col0 := count                                                                                                                                                                                 
     - Aggregate(FINAL) => [count:bigint]                                                                                                                                                               
             count := "count"("count_3")                                                                                                                                                                
         - Exchange[GATHER] => count_3:bigint                                                                                                                                                           
             - Aggregate(PARTIAL) => [count_3:bigint]                                                                                                                                                   
                     count_3 := "count"(*)                                                                                                                                                              
                 - Filter[false] => []                                                                                                                                                                  
                     - TableScan[kafka:KafkaTableHandle{connectorId=kafka, schemaName=s1, tableName=t2, topicName=s1.t2, keyDataFormat=dummy, messageDataFormat=dummy}, original constraint=true] => []

**Comment by lvxin1986** [comment]
I have encountered the same problem,anyone could explain why?

**Comment by dain** [comment]
My guess is the Kafka broker is reporting that there are no partitions, so the Kafka connector is telling presto there is no data.  When Presto see there is no data it adds a "false" filter, and when the plan is optimized the whole thing folds to a no data node.  The code that is looking for the partitions is here:

  https://github.com/facebook/presto/blob/master/presto-kafka/src/main/java/com/facebook/presto/kafka/KafkaSplitManager.java#L90

**Comment by yuananf** [comment]
Oh, it appears that the topic has some weird problem, not a problem anymore.
