### ISSUE TITLE
Presto cli supports --timeout

### ISSUE THREAD

**Issue by yaoxin226** [facebook/presto#2804]
This will be useful for debugging.  When debug presto step by step for a long time, I always got presto-cli timed out with following error
```
Query is gone (server restarted?)
```

**Comment by harunurhan** [comment]
@yaoxin226 Hi, I can do it, if nobody is working on it.

As far as I could see, it is currently 2 minutes. Should it be in minutes or in seconds, which one would be better?

**Comment by electrum** [comment]
This is actually not a CLI issue. There are two related server config variables:
* `query.client.timeout` -- if the client does not heartbeat within this period, the server fails the query with the `ABANDONED_QUERY` error
* `query.max-age` -- the server will expire queries older than this (if there are more than `query.max-history` queries awaiting expiration)

**Comment by yaoxin226** [comment]
I think there are two situations:
* How long should server wait if it hasn't receive a heartbeat from client (Already configurable as @electrum mentioned)
* How long should client wait if it hasn't receive a response from server ( I think Presto is missing this )

**Comment by electrum** [comment]
At, yes, you are correct, that "server is gone" can happen here:

https://github.com/facebook/presto/blob/master/presto-client/src/main/java/com/facebook/presto/client/StatementClient.java#L254

We could make that configurable. Probably "client request timeout" or similar.

**Comment by harunurhan** [comment]
@electrum I was thinking to add this option to ClientOptions and pass it to ClientSession then finally use it in StatementClient.

Do you think, this is the right approach here? 

FYI: I am literally new to codebase and everything so is there anything I need to know before starting. Thanks!

**Comment by harunurhan** [comment]
@electrum @yaoxin226 
I implemented it in on my fork's branch. I just want to show it before PR. You can have look at it here https://github.com/harunurhan/presto/commit/53121ecbc9eb9316b5147fdc115cc4c1bc0890c1
All tests passed and seems to work as far as I could test.

**Comment by electrum** [comment]
This looks like a good start. One comment is to use the Airlift Duration object, since that is both easier for users (can say "2m" or "30s") and avoids needing to specify the unit in code.

**Comment by harunurhan** [comment]
@electrum 
Thanks for your help, changed it here:
https://github.com/harunurhan/presto/commit/a18b09ac1ae793e0856ea240578d902594dcd682

**Comment by electrum** [comment]
Please create a pull request!

**Comment by electrum** [comment]
0.129 will have `--client-request-timeout`
