### ISSUE TITLE
Presto should be upgraded to use Parquet 1.6

### ISSUE THREAD

**Issue by nezihyigitbasi** [facebook/presto#2806]
Presto is currently using Parquet 1.3.2, a bit old. It would be nice if Presto is upgraded to use Parquet 1.6, which is recently released.

**Comment by damiencarol** [comment]
+1 for this one even if ORC is more fast currently.

**Comment by zhenxiao** [comment]
+1
in Parquet 1.3.2, stats is not available, 1.6.0 opens the oppotunity to use stats to filter out row group and column chunks, just as how the new ORC reader is doing

**Comment by dain** [comment]
Can one of you that uses Parquet sent a pull request?

**Comment by zhenxiao** [comment]
Shall the shaded jars be updated? I send a PR there:
https://github.com/prestodb/presto-hive-apache/pull/13

**Comment by electrum** [comment]
Merged #2926
