### ISSUE TITLE
Presto requires architecture amd64 on Linux (found i386)

### ISSUE THREAD

**Issue by arun6384** [facebook/presto#2807]
Hello,

Presto server versions tried: 0.92, 0.97, 0.100
We have been able to extract presto in our Red Hat Linux environment.
However, post configuration after we run the launcher the launcher.log displays an error 

"ERROR: ld.so: object '/home/hadoop/prestoDB/presto-server-0.100/bin/procname/Linux-x86_64/libprocname.so' from LD_PRELOAD cannot be preloaded: ignored.
Presto requires architecture amd64 on Linux (found i386)"

1. java version "1.8.0_05"

2. Hardware Configuration:
Architecture:                x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:                  Little Endian
CPU(s):                        8
On-line CPU(s) list:      0-7
Thread(s) per core:     1
Core(s) per socket:      1
Socket(s):                     8
NUMA node(s):            1
Vendor ID:                   GenuineIntel
CPU family:                  6
Model:                         45
Stepping:                     2
CPU MHz:                   2200.000
BogoMIPS:                  4400.00
Hypervisor vendor:      VMware
Virtualization type:       full
L1d cache:                  32K
L1i cache:                   32K
L2 cache:                    256K
L3 cache:                    20480K
NUMA node0 CPU(s):     0-7

Red Hat Linux details.
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.5 (Santiago)
Release:        6.5
Codename:       Santiago

Kindly let me know what could be the root cause for this issue.

Thanks,
Arun

**Comment by electrum** [comment]
Are you running a 32-bit version of Linux? Please post the output of `uname -a`.

**Comment by electrum** [comment]
Actually, you might be running a 32-bit version of Java. Please also post the full output of `java -version`.

**Comment by arun6384** [comment]
Hi electrum,
The Red Hat Linux version and java versions we have installed are 64-bit.
Please find the requested information below. 

Output of "uname -a"
Linux namenode 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 16 06:12:23 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

Full output of "java -version"
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) Server VM (build 25.5-b02, mixed mode)

Thanks for the reply,
Arun

**Comment by electrum** [comment]
Thanks. That shows you are running the 32-bit JVM (you would see 64-bit in the output). Presto requires a 64-bit JVM. Please try 8u45.

**Comment by electrum** [comment]
The output should look like this:
```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by arun6384** [comment]
Thank You Electrum. Replacing the exisiting JVM with 64-bit works.

**Comment by cantepeli** [comment]
Hi arun6384 

How  did you replace  JVM 32-bit to 64-bit please give us that info
