### ISSUE TITLE
Query with many CASE/WHEN statements fails with java.lang.VerifyError

### ISSUE THREAD

**Issue by andytinycat** [facebook/presto#2826]
Some of our analysts like to use a lot of CASE/WHEN statements for classifying things.

In queries with many CASE/WHEN statements (seems to be about >75, though it varies - I've seen queries with 100+ succeed), the query will consistently fail with an exception like this:

```
Presto error: Query 20150318_103732_07497_i5v8q failed: java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    com/facebook/presto/$gen/PageProcessor_13497.filter(Lcom/facebook/presto/spi/ConnectorSession;Lcom/facebook/presto/spi/block/Block;Lcom/facebook/presto/spi/block/Block;Lcom/facebook/presto/spi/block/Block;Lcom/facebook/presto/spi/block/Block;I)Z @44: nop
  Reason:
    Expected stackmap frame at this location.
  Bytecode: 
    <2000+ lines of bytecode snipped>
  Stackmap Table:
    <2500+ lines snipped>
```

This happens with Presto versions 0.86, 0.89, 0.92 and 0.96 (which we're currently running). I'm upgrading to 0.101 soon so I'll see if it affects that version.

We usually work around this by rewriting them into more broad CASE/WHENs or using regexes. I have a feeling queries with this many CASE/WHENs are pathological in nature.

Any ideas why this might be happening?

**Comment by cberner** [comment]
Yep, that's a known issue. The only thing you can try right now is enabling the interpreter, which is vastly slower. https://github.com/facebook/presto/issues/2568

**Comment by andytinycat** [comment]
Thanks for confirming. We'll continue to work around it.

**Comment by electrum** [comment]
If this is still problem in 0.101, please reopen and post a stack trace, and possibly a query that reproduces the issue (maybe `VALUES` or the TPCH connector)? This looks like a different issue than the bytecode limit and might be a bug in the code generator.
