### ISSUE TITLE
hive.max-split-iterator-threads parameter

### ISSUE THREAD

**Issue by nezihyigitbasi** [facebook/presto#2840]
In ``HiveClientConfig`` I see that there are two parameters ``hive.max-split-iterator-threads`` and ``hive.max-global-split-iterator-threads``, and as far as I can see ``hive.max-split-iterator-threads`` is not even used. What's the difference? And if it's not used I can create a PR to get rid of it.

**Comment by cberner** [comment]
Yep, that was an old config option that no longer does anything. Please send a PR! :)

**Comment by nezihyigitbasi** [comment]
@cberner What's the reason that the other parameter has "global" in its name? It's confusing. Should we rename it too? What do you think?

**Comment by cberner** [comment]
I think it's because it controls the total number available to all queries, whereas this one probably just controlled the number that each query could use.

Yep, lets rename it (make sure to note that in the release notes). Thanks!

**Comment by electrum** [comment]
@nezihyigitbasi Please submit a new PR if you want to rename the current "global" config. I merged the PR to remove the unused config.
