### ISSUE TITLE
Limit thread creation in Hive split creation

### ISSUE THREAD

**Issue by dain** [facebook/presto#2849]
The thread pool for Hive split creation is unbounded, which creates massive load on the coordinator when processing large partitions.  The thread pool should be capped and `BackgroundHiveSplitLoader.loadSplits` should be limited to create only a fixed number of splits in one run.  This will cause threads to be more fairly shared across queries.

**Comment by cberner** [comment]
Actually, it is limited. See the `HiveSplitManager` constructor: `new BoundedExecutor(executorService, hiveClientConfig.getMaxGlobalSplitIteratorThreads())`
