### ISSUE TITLE
prestodb create table syntax error

### ISSUE THREAD

**Issue by krisdwang** [facebook/presto#2855]
I followed presto 0.100 document to try to create a mysql table, sql is under here:

CREATE TABLE orders (
  orderkey bigint,
  orderstatus varchar,
  totalprice double,
  orderdate date
)

but I got error message: 'Query 20150504_095508_00067_t9ru3 failed: line 1:21: mismatched input '(' expecting {'.', 'AS'}'

is it a defect about presto?

**Comment by yuananf** [comment]
Currently in presto-0.101, create table is only enabled in hive connector and raptor connector.

**Comment by electrum** [comment]
This syntax was added in 0.101.
