### ISSUE TITLE
limit condition is very slow

### ISSUE THREAD

**Issue by xuyang198711** [facebook/presto#2867]
now, the count of "select * from table where id like ‘%XXX%’ " is 9;
I execute "select * from table where id like ‘%XXX%’ limit 9",it is very fast;
but i execute "select * from table where id like ‘%XXX%’  limit 10",it is very slow,it will query all of the data!
why?  i want the result very fast,What should I do？

I'm sorry, my english is not good!

**Comment by cberner** [comment]
That's probably because it's easy to find 9 rows that match your regex. However, it may need to scan a lot more data to find a 10th.
