### ISSUE TITLE
Add support for scalar subqueries

### ISSUE THREAD

**Issue by lvxin1986** [facebook/presto#2878]
Scalar sub queries are not supported.  For example:
```sql
SELECT *
FROM nation
WHERE nation KEY >= (SELECT nation KEY FROM nation WHERE NAME ='ALGERIA' LIMIT 1)
```

**Comment by parul-agarwal** [comment]
I am also facing this issue.Is this issue fixed?

**Comment by kokosing** [comment]
I can take this one if nobody is already working on this.

**Comment by kokosing** [comment]
I think that simply solution to support uncorrelated scalar subqueries (that not using outer tables and return single row with one column) could be a following rewrite:

From
```
SELECT *
FROM nation
WHERE nationkey = (
  SELECT nationkey FROM nation WHERE NAME = 'ALGERIA' LIMIT 1
)
```
to
``
WITH sub1 AS (
  SELECT nationkey FROM nation WHERE NAME ='ALGERIA' LIMIT 1
)
SELECT n.nationkey, n.name, n.regionkey, n.comment
FROM nation n, sub1
WHERE n.nationkey = sub1.nationkey;
```

I don't know how correlated subqueries are important, anyway they seem to be much more complicated to execute.

What do you guys think about?

**Comment by kokosing** [comment]
It looks like a workaround, I am not sure about performance (execution) of it as join order may have importance here.

**Comment by martint** [comment]
Correlated subqueries are a lot more complicated and require some rearchitecting of the analyzer and planner to support without too many hacks.

For uncorrelated subqueries, yes, that's exactly how you'd modeled them. But two things:
* It has to ensure the scalar subquery produces exactly one value (or fail otherwise)
* It needs to execute as a broadcast join. Otherwise the query will turn into a single-node query due to skew in the join key.

No one's working on this, yet, so go for it!

**Comment by kokosing** [comment]
As I understand scalar query may return single value or not at all (then scalar returns null).

To ensure above condition (behaviour) I think I need to add new plan node - ScalarNode, which then will be translated into proper operator. Adding a new plan node requires a lot of work. Do you think it is a good idea? Or should I hack already existing plan node like ProjectNode? What do you think?

**Comment by kokosing** [comment]
I also think that such ScalarNode would be helpful execute join as a broadcast join.

**Comment by kokosing** [comment]
@martint What do you mean by broadcast join? How can I set this or check?

I did a rewrite and I see plan fragment with join has plan distribution FIXED and fragments with table scan have distribution SOURCE. So it looks like it is not going to be a single-node query, am I right?

**Comment by kokosing** [comment]
According to my current understanding this is what I am going to do.

1. rewrite scalar query to join
2. mark join with some property that it is going to join with results from scalar function
3. In AddExchanges#visitJoin if a joinNode joins results from scalar then it will be as broadcast join
4. Modify physical plan for plan fragment with join  with results from scalar that it will have an intermediate operator (between ExchangeOperator and HashBuilderOperator) which will check if scalar results returned at most single row.

Another option would be add a separate plan node, a ScalarNode (represents operation which returns a single value), then the solution would be less hacky but it would require much more coding.
1. rewrite scalar query to join with a ScalarNode
2. In AddExchanges#visitScalarNode I would create an Exchange which gathers all results
3. In AddExchanges#visitJoin if join joins scalarNode then it will go with a broadcast join
4. Create phisical plan for ScalarNode, create ScalarOperator which will ensure that scalar query returned at most single value.

For now I am going with the first option. All comments are more than welcomed : )

CC: @martint

**Comment by kokosing** [comment]
After some thinking I decided to go with option two (add ScalarNode). I have no heart to break the code cleanness ProjectNode or JoinNode.

**Comment by martint** [comment]
Yeah, a separate plan node makes more sense. It will make it easier to ensure the invariants are handled correctly and will be easier to map to the future plan structure/optimizer later on.
