### ISSUE TITLE
Investigate long planning time on Hive table with many partitions

### ISSUE THREAD

**Issue by dain** [facebook/presto#2881]
A query like `select * from t limit 10` takes several minutes in planning for Hive tables with > 10k partitions.  This is easy to reproduce.

**Comment by erichwang** [comment]
This is the stack trace on the coordinator: https://gist.github.com/erichwang/6d180ffa7ef106b79258
It looks like we are blocked on com.facebook.presto.hive.metastore.CachingHiveMetastore.getPartitionsByNames when fetching splits

**Comment by cberner** [comment]
This should help https://github.com/facebook/presto/pull/2887

But we probably need to refactor the way that partition discovery works, so that we don't need to enumerate all partitions during exchange planning to really make this fast
