### ISSUE TITLE
presto-odbc

### ISSUE THREAD

**Issue by lvxin1986** [facebook/presto#2884]
Hi,
Presto.Is there any available odbc for prestoc?
I have used the presto-odbc:https://github.com/prestodb/presto-odbc
But I found that the presto-odbc is too poor of basic funtions to be used.eg:It could not read the columns,if the column's type is  Date or Time. It seems there is no people n charge of this project.
So,is there another available odbc for presto ?

**Comment by nezihyigitbasi** [comment]
There is also https://github.com/treasure-data/prestogres for PostgreSQL maintained by Treasure Data, you can take a look at that.

**Comment by cberner** [comment]
That's the only odbc driver that I'm aware of. We would welcome patches, if you find issues with it!
