### ISSUE TITLE
Raptor Storage delete data on DROP TABLE

### ISSUE THREAD

**Issue by mmax5** [facebook/presto#2923]

**Comment by electrum** [comment]
This is coming soon :)

**Comment by teejteej** [comment]
Is there a workaround to know which files to remove from storage if a complete schema with all tables can be dropped?

**Comment by electrum** [comment]
As a general note, Raptor should currently be considered experimental. When we feel it is ready for everyone to use, we will document and publicize it.

I am adding transactional logging of every object created by Raptor, which will allow safe online storage reclamation.

It is possible to manually delete all the shard files for a dropped table (if you have a list from before it was dropped), but for testing purposes, I recommend doing a wipe/reload.

**Comment by martint** [comment]
@electrum this is already supported, no?

**Comment by electrum** [comment]
No, I am working in this now.

**Comment by electrum** [comment]
This was merged a while ago.
