### ISSUE TITLE
Can't use comparisions = for UUID fields in Cassandra catalog

### ISSUE THREAD

**Issue by gilbertofp16** [facebook/presto#2927]
I tried to use  WHERE FieldUUID = 'UUID' in Cassandra database, and I got the error 'Error fetching cassandra partitions', I executed this select:

SELECT * FROM useralbum WHERE  iduser =  'afc123d4-0e7b-4c9f-b815-864f520c79c3' limit 1;

Also I tried this:

SELECT * FROM useralbum WHERE NOT iduser <> 'afc798d4-0e7b-4c9f-b714-864f520c79c3' limit 1;

But I have the same error for both, if I use (SELECT * FROM useralbum WHERE iduser <> 'afc798d4-0e7b-4c9f-b714-864f520c79c3' limit 1;) it works perfectly, and also if I use other fields different than UUID I can do the select with where and use =. 

I want to request please a solution for comparison of UUID fields in Cassandra.

My Cassandra version: 4.2
Presto version: presto-server-0.102

**Comment by fernando-goncalves-movile** [comment]
I have the same issue. It would be great if we find the solution!
