### ISSUE TITLE
"Connection already closed" error in JdbcRecordCursor

### ISSUE THREAD

**Issue by AshwinJay** [facebook/presto#2934]
Hi, In the `com.facebook.presto.plugin.jdbc.JdbcRecordCursor`'s `close()` method the resources are listed in incorrect order. This results in the connection getting closed even before statement or the resultSet.

Some Drivers may be forgiving, but I was trying to use SQLite and it throws an exception if the connection is closed before the statement/resultSet. 

On [master](https://github.com/facebook/presto/blob/master/presto-base-jdbc/src/main/java/com/facebook/presto/plugin/jdbc/JdbcRecordCursor.java#L218):
```
// use try with resources to close everything properly
try (ResultSet resultSet = this.resultSet;
		Statement statement = this.statement;
		Connection connection = this.connection) {
	// do nothing
}
```

https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html says `Note that the close methods of resources are called in the opposite order of their creation`.

So, just changing the order like this made it work:
```
// use try with resources to close everything properly
try (Connection connection = this.connection;
		Statement statement = this.statement;
		ResultSet resultSet = this.resultSet) {
	// do nothing
}
```

Regards.

**Comment by AshwinJay** [comment]
Also, I noticed that the `connection.close()` method gets called twice. Once at the end of the page iteration and then again at `finish()`.

I'm pretty sure many JDBC drivers are OK with this but some are more strict. See my attached screenshots that show the 2 times the DB connection close was called for the same user query.

(1)
![screen shot 2015-05-17 at 2 22 04 pm](https://cloud.githubusercontent.com/assets/222056/7674663/2048a694-fce2-11e4-80a5-6542dae24790.png)

(2)
![screen shot 2015-05-17 at 2 22 24 pm](https://cloud.githubusercontent.com/assets/222056/7674664/20498028-fce2-11e4-9a37-7bdf633a596c.png)

**Comment by martint** [comment]
Good catch! Would you like to submit a pull request to fix it?

**Comment by AshwinJay** [comment]
@martint  I have submitted a PR but the build broke. Not sure if it is because of my patch. Is there anything I have to do like retrigger it?

**Comment by martint** [comment]
Thanks! We'll look at it soon.

The build failure seems unrelated. Don't worry, we'll take care of it.
