### ISSUE TITLE
Enable streaming results for JDBC connector

### ISSUE THREAD

**Issue by electrum** [facebook/presto#2960]
In `JdbcRecordCursor`:

For PostgreSQL, we need to call `setAutoCommit(false)` on the `Connection`: https://jdbc.postgresql.org/documentation/head/query.html

For MySQL, we need to call `enableStreamingResults()` on the MySQL `Statement` (see `ShardIterator` for an example).

Since we need specific logic for different databases, we should add a `getStatement(connection)` method to `JdbcClient` that can do the customization.

**Comment by Myrthan** [comment]
I'm claiming this:)

**Comment by yuananf** [comment]
@Myrthan Are you still working at this?

**Comment by Myrthan** [comment]
Yes but I met some problems in customising statement. Every database need different "things" to prepare statement so this is not simply launch few methods depends on kind of database.
