### ISSUE TITLE
SqlBaseParser class is missing in latest build/commit

### ISSUE THREAD

**Issue by PPrabhaakaran** [facebook/presto#2980]
I downloaded the latest from github, but unable to compile because the following file have reference s to "SqlBaseParser" class. But I do not see the SqlBaseParser file/class anywhere in the package in the github.

Please help.

presto/presto-parser/src/main/java/com/facebook/presto/sql/parser/SqlParser.java

Error:(74, 65) java: cannot find symbol
  symbol:   class SqlBaseParser
  location: class com.facebook.presto.sql.parser.SqlParser

**Comment by electrum** [comment]
Please see Building section in the README for the repository. You have to run a command line Maven build first to generate the parser from the ANTLR grammar.

Reopen the issue if this doesn't fix it.
