### ISSUE TITLE
Does Presto support fault tolerance now ?

### ISSUE THREAD

**Issue by hlsc** [facebook/presto#3051]
Does Presto support fault tolerance now ?I just tried to kill some nodes when a query is running,the query is also finished,does Presto has been Integrated the fault tolerance?

**Comment by martint** [comment]
If a Presto node dies, any running queries with tasks assigned to that node will fail. 

There are some forms for fault tolerance built into Presto, though. For instance, requests between nodes will retry if there are any communication failures. Some connectors, such as the one for Hive, will also retry calls to the metastore or hdfs in case of errors.
