### ISSUE TITLE
TopNRowNumber should support equality

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3068]
The following queries should both optimize to use `TopNRowNumber`:
```sql
SELECT x FROM (SELECT x, row_number() OVER (ORDER BY x) rn FROM ...) WHERE rn = 1;

SELECT x FROM (SELECT x, row_number() OVER (ORDER BY x) rn FROM ...) WHERE rn <= 1;
```
Currently, only the `<=` version works. There are actually two cases to support:

* Convert `= 1` to `<= 1`, as they are equivalent (only works for `1`, not other values).
* Convert `= x` to `TopNRowNumber` and add a `= x` filter on top.

**Comment by yuananf** [comment]
May I try this one?

**Comment by yuananf** [comment]
I have a question here:
Should the following query be optimized?
```
SELECT x FROM (SELECT x, row_number() OVER () rn FROM ...) WHERE rn = 5 OR rn = 20;
```

**Comment by electrum** [comment]
I forgot for the `ORDER BY` in the description which is necessary for `TopNRowNumber`. Without an ordering, it always uses the `RowNumber` operator, regardless of the filter. I will update the description.

**Comment by electrum** [comment]
@yuananf You are correct, there is a more general case that can be supported. In that example, we could use a `TopNRowNumber` with a limit of `20` and add a filter on top. I don't know how difficult that would be to do in the optimizer, or if we have any code to help pull out the range. @martint might know

**Comment by yuananf** [comment]
This was fixed now.
