### ISSUE TITLE
TimestampOperators.castFromSlice doesn't allow to specify a timezone

### ISSUE THREAD

**Issue by ilfrin** [facebook/presto#3098]
I get the following error
```
presto:default> select cast ('2015-01-01 03:15:16 UTC' as timestamp);
Query 20150615_125549_00002_6vtv2 failed: Invalid format: "2015-01-01 03:15:16 UTC" is malformed at " UTC"
```
while when I express this in a different way I get
```
presto:default> select timestamp '2015-01-01 03:15:16 UTC';
            _col0            
-----------------------------
 2015-01-01 03:15:16.000 UTC 
(1 row)
```
(the latter outputs a timestamp with time zone, but that's an irrelevant difference here)

the code responsible for this is the `TimestampOperators.castFromSlice()` method which calls `DateTimeUtils.parseTimestampWithoutTimeZone()` method. 

So the question is whether this is intentional or just the way it is now? Shouldn't this operator allow to pass in values with an arbitrary timezone as well?

**Comment by haozhun** [comment]
Does `parse_datetime` or `from_iso8601_timestamp` work for you?

By the way, a cast to timestamp with timezone should look like `select cast ('2015-01-01 03:15:16 UTC' as timestamp with time zone);`. Unfortunately such a cast doesn't exist today.

**Comment by ilfrin** [comment]
I'd rather use more or less standard SQL casting. Anyway it's just a workaround. 

also I don't want to cast to a type timestamp with timezone, I want the string to be interpreted in an arbitrary timezone, not the client timezone as it is now. 

My question remains whether that is intended behavior or not, if not I can fix it, like I said I don't see a reason why this shouldn't work for both cases but maybe I'm not seeing it all here. Although just using the `DateTimeUtils.parseTimestamp()` method instead doesn't work since that one does more than it's name suggests, it packs the timezone information into the long value by doing some bit shifting, so in output I get a date round the year 186292 ;)

**Comment by haozhun** [comment]
I'm not sure if it is intended that `select cast ('2015-01-01 03:15:16 UTC' as timestamp with time zone)` doesn't work today. I will ask my teammate. In the mean time, you can try the workaround.

For your question about`cast (... as timezone)`, `timestamp` type does not have time zone. Putting date, time and timezone in `timestamp` is equivalent to putting date and time in a date type. I agree that the literal timestamp constructor is misleading in that it can constructs both `timestamp` and `timestamp with time zone`. But this behavior is defined in ISO/IEC 9075-2:2011(E) 5.3 Syntax Rules 27.

    presto:di> select cast (timestamp '2015-01-01 03:15:16 UTC' as timestamp);
               _col0
    -------------------------
     2014-12-31 19:15:16.000
    (1 row)

The bit shifting thing is internal presto implementation details and shouldn't be visible to the user. That's how we put a timezone and a timestamp in one 8-byte integer. If you get a date around 186292, that's a bug. Please provide more details.

**Comment by dain** [comment]
There is no operator registered to cast from `VARCHAR` to `TIMESTAMP WITH TIME ZONE`

**Comment by haozhun** [comment]
@dain According to spec 6.13 General Rules 17 a ii, 

> If `TD` (target data type) is the datetime data type `TIMESTAMP WITHOUT TIME ZONE`, and a valid value of the data type `TIMESTAMP(TSP) WITH TIME ZONE` can be determinted, then let `TV` (target value) be the value of

>     CAST ( CAST ( VE AS TIMESTAMP(TSP) WITH TIME ZONE ) AS TIMESTAMP(TSP) WITHOUT TIME ZONE )

**Comment by dain** [comment]
@ilfrin the cast should work as you expected.  This will go out with the next release.

**Comment by ilfrin** [comment]
@dain thanks for the quick response, I found this while running the product tests we wrote in different than standard server/client timezone configurations. 

This change together with the other pull requests in flight (INSERT INTO, execUpdate(), etc) are a prerequisite before I can rebase and run the product tests against the latest presto codebase.
