### ISSUE TITLE
documentation error for Presto 0.107

### ISSUE THREAD

**Issue by pberling8** [facebook/presto#3138]
On page https://prestodb.io/docs/current/functions/comparison.html, the header of the table below shows "a = a" when it should be "a = b".

a 	b 	a = a 	a <> b 	a DISTINCT b 	a NOT DISTINCT b
1 	1 	TRUE 	FALSE 	FALSE 	TRUE
1 	2 	FALSE 	TRUE 	TRUE 	FALSE
1 	NULL 	NULL 	NULL 	TRUE 	FALSE
NULL 	NULL 	NULL 	NULL 	FALSE 	TRUE

**Comment by yaoxin226** [comment]
Thanks @pberling8 , it should be fixed by #3139

**Comment by electrum** [comment]
Fix merged
