### ISSUE TITLE
Add CREATE TABLE AS SELECT WITH NO DATA statement

### ISSUE THREAD

**Issue by arhimondr** [facebook/presto#3145]

**Comment by electrum** [comment]
We can add that. Work around for now: LIMIT 0

**Comment by arhimondr** [comment]
We are using "WHERE 0=1" for now, which is similar. But it still does the TableWrite tasks distributions, and creates empty files in hdfs. So, we should either optimize it #3146 , or add WITH NO DATA keyword, or do both.

**Comment by electrum** [comment]
I agree, we should support both, and the optimization should apply in either case.

**Comment by Myrthan** [comment]
Okay I can try this one for next two days.

**Comment by kokosing** [comment]
It looks like @Myrthan has stopped working on this, so if she/he does not mind I can continue his work and take over this.
