### ISSUE TITLE
TopNRowNumber optimizer should support composite expressions

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3147]
The following optimizes correctly:
```sql
WITH t AS (SELECT x, row_number() OVER (ORDER BY x) rn FROM ...)
SELECT x FROM t WHERE rn <= 10;
```
But these do not:
```sql
WITH t AS (SELECT x, row_number() OVER (ORDER BY x) rn FROM ...)
SELECT x FROM (SELECT x FROM t WHERE rn <= 10) WHERE rn <= 5;

WITH t AS (SELECT x, row_number() OVER (ORDER BY x) rn FROM ...)
SELECT x FROM (SELECT x FROM t WHERE rn <= 10) WHERE x IS NOT NULL;
```

**Comment by yuananf** [comment]
I will try this one.

**Comment by yuananf** [comment]
I'm almost finishing it, but the cases below should be discussed:

```
WITH t AS (SELECT x, row_number() OVER (ORDER BY x) rn FROM ...)
SELECT x FROM t WHERE rn >= 10 limit 5
```

```
WITH t AS (SELECT x, row_number() OVER (ORDER BY x) rn FROM ...)
SELECT x FROM t WHERE rn <= 3 or rn > 10 limit 5
```

My thought is as follows:
For the first case
* rewrite it to ```rn >= 10 and rn <= 14```

For the second case we have two choices
* rewrite the second one according to the range of ```rn```, and generate a new range of ```rn```
* add a ```LimitNode``` on top of TopNRowNumber

@electrum any suggestions?

**Comment by yuananf** [comment]
And another question here, for the case below
```
WITH t AS (SELECT x, row_number() OVER (PARTITION BY y, ORDER BY x) rn FROM ...)
SELECT x FROM t  limit 5
```
What should the ```limit 5``` behave?
Limit each partition of  ```y``` or limit the whole result?

**Comment by yuananf** [comment]
This was fixed now.
