### ISSUE TITLE
Support Limit All

### ISSUE THREAD

**Issue by akshatnair** [facebook/presto#3158]
In some database like PostsgreSQL, MySQL "Limit All" has the same effect as eliminating the LIMIT clause from a query; it returns all the rows. Currently it gives error in Presto that the argument of Limit clause must be an integer.

**Comment by electrum** [comment]
I tried in MySQL 5.6 and it seems not to be supported, so this might be only be in PostgreSQL. I'm curious, is this a compatibility issue for you, such as a tool that generate queries?

It is not an unreasonable feature (especially for PostgreSQL compatibility), but it is strange (if you don't want limit, leave it out).

**Comment by akshatnair** [comment]
Yes MySQl does not support it, my mistake, I misread one of the document. And yes users can always leave out the limit clause but I think some tools might generate limit clause by default and use All there to fetch all rows. This is needed for PostgreSQL compatibility and an easy enhancement. 

Other products that supports ALL in Limit clause are Vertica and Apache Drill

**Comment by kokosing** [comment]
Shouldn't this issue be closed, as #3161 is closed and merged? Is there anything left to be done here?
