### ISSUE TITLE
Remove boxing for IN lists of primitives

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3163]
https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/gen/InCodeGenerator.java#L129

**Comment by sopel39** [comment]
I would like to try this one

**Comment by petroav** [comment]
I think this can be closed.

**Comment by raghavsethi** [comment]
Yes, we have solved all the problems we know of related to IN lists.
