### ISSUE TITLE
Use direct switch for small IN lists of small primitives

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3164]
If all of the constants fit in an `int` (less than `2^32`), we can switch on the values directly, rather than on the hash code. This removes both the hash computation of the lookup value and the extra comparison when the hash matches.

https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/gen/InCodeGenerator.java#L102

**Comment by cberner** [comment]
This still needs to be implemented

**Comment by zjshen** [comment]
I'd like to take care of this issue.

**Comment by zjshen** [comment]
Here's my fix. Please let me know if I'm doing it on the right way. Thanks!

https://github.com/facebook/presto/pull/3610
