### ISSUE TITLE
Add more failure info to QueryCompletionEvent

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3178]
We need to know the task ID and the machine on which the failure occurred. This helps with finding logs related to a failure, correlating machines with higher than average failure counts, etc.

**Comment by monkey-mas** [comment]
Let me try this one.

@electrum 
Can you be more specific about _machine_ information? I'm not sure what kind of information you have in mind. If you referred to `nodeInstanceId`[1] in TaskInfo as _machine_, it should be easy to add it to QueryCompletionEvent.

[1] https://github.com/facebook/presto/blob/c244ebaa629638fc0035f38ddc1c07948dba5100/presto-main/src/main/java/com/facebook/presto/execution/TaskInfo.java#L54
