### ISSUE TITLE
Query stalls in Presto 0.108

### ISSUE THREAD

**Issue by xerial** [facebook/presto#3191]
Although I couldn't find the exact cause, but some queries started to stall in Presto 0.108. For example, the following queries stalled:
```
SELECT * FROM nasdaq TABLESAMPLE BERNOULLI (1);
SELECT count(l_linenumber) FROM tpch_s1.lineitem TABLESAMPLE BERNOULLI(1)
```

This is not specific to TABLESAMPLE operation, since the other type of queries (e.g., joins) also stalls. 

This bug might be related to our connector implementation, but it looks like when skipping entries this stall happens. Please let me if you know anything on this problem. 

Thanks.

**Comment by wyukawa** [comment]
I also encountered the similar problem.

https://groups.google.com/forum/#!topic/presto-users/Aw3XOhl5j7w

I try to use presto 0.108 + jdk1.8.0_45 + HDP 2.1 + CentOS 6.5.

I use hive connector.

Some queries don't return at presto 0.108, but return at presto 0.107.

Thanks.

**Comment by cberner** [comment]
Could you look in the web ui and tell me what the status of the query is? In particular, it would be helpful to know:
* does the UI report it as BLOCKED?
* what state are the different stages in?
* for stages that are still running, what state are the tasks in?

**Comment by cberner** [comment]
Also, when you say "stall" do you mean that it never finishes, or does it just take a long time?

**Comment by xerial** [comment]
@cberner 
- Yes. It shows BLOCKED at the root stage, and the child stages are in RUNNING state.
- By `stall`, I mean it never finishes and without any progress in `outputPositions` count.

**Comment by cberner** [comment]
I see. What state are the tasks in the child stage in?

**Comment by xerial** [comment]
All of the child tasks are in RUNNING state.  

I'm going to check the heap dump or thread stacks (/v1/thread) to see where the query is blocked.

**Comment by electrum** [comment]
I'm seeing an issue where stages never get any tasks scheduled. Might be the same problem. Did not happen with 0.107.

It occurred twice after restart where we sent ~10 queries at all once. All were stuck the same way and never recovered. No other queries running. Subsequent queries were fine.

**Comment by cberner** [comment]
@xerial also take a look at the task info (json document) which you can find by clicking on the link from the task, on the query page. If you don't mind sharing the info in there, it would be helpful to debugging too.

**Comment by yuananf** [comment]
Is this helpful?
When restarting a presto cluster, execute ```show tables```, it also never finished, and the web page looks like below:

![timline 20150630140035](https://cloud.githubusercontent.com/assets/4101738/8424711/6f706b92-1f30-11e5-912c-6d9499d6a77c.png)

**Comment by wyukawa** [comment]
My case is the following.

http://gyazo.com/83a8c1e2b52b2a3e28821cf954fd5f34

presto query is the following
```
WITH 
... AS 
    (
    SELECT
       .....
    FROM
        presto_view
    WHERE 
        ...
    GROUP BY 
        ...
    )
SELECT
    ....
    SUM(...)
        OVER(
            PARTITION BY
                ...
        ) AS ...
FROM
    ...
```

**Comment by xerial** [comment]
@cberner 
Sure. After excluding some private information, I'll share it.

**Comment by xerial** [comment]
Here is the json data of the tasks of a stalled query: 
https://gist.github.com/xerial/b14041846ff246849275

![20150630_071237_06262_zieat](https://cloud.githubusercontent.com/assets/57538/8425933/1cecf294-1f46-11e5-939e-296c4ed2b3a7.png)

It looks like the child tasks already finished processing the data, but the parent task is still waiting the result.

**Comment by cberner** [comment]
@xerial it looks like the problem is that the TableScan is hung/slow. In your screen shot it shows that none of the splits have finished running, and from the json stats it looks like none of the tasks have produced output. For example `20150630_071237_06262_zieat.1.0` shows 0 `outputPositions`. Can you try running jstack on one of your workers to see if the TableScan thread is stuck?

**Comment by dain** [comment]
@yuananf we have seen that one internally.  There is some bug where a stage fails immediately during setup, but the query misses the notification.

@xerial If you open the info for one of the table scan tasks (click the task id in the table). Then look for "getOutputCalls", wait a minute and check it again.  The number should increment each time the output method on the operator is called.  There are stats for each of the main methods of an operator, so using this technique, you can see if the operators are still being invoked.  If they are not, it is likely all of the worker threads are hung.

**Comment by wyukawa** [comment]
Here is the jstack result of presto 0.108 worker in my case

https://gist.github.com/wyukawa/2f8d09a03aef8b844370

**Comment by cberner** [comment]
@dain I think this will fix the issue with stages that fail during setup not failing the query: https://github.com/facebook/presto/pull/3204

It doesn't explain some of the other hangs though

**Comment by cberner** [comment]
We found this bug https://github.com/facebook/presto/pull/3212 which would cause stalls for JOINs. Not sure about the table sample ones though

**Comment by xerial** [comment]
This might be related to our connector implementation. Let me close this ticket for now. 
If we can find another cause, we will open a new ticket. 

Thanks!
