### ISSUE TITLE
Include error location information for unresolved functions

### ISSUE THREAD

**Issue by cberner** [facebook/presto#3203]
Queries like `SELECT 1 = '1'` fail with "Operator EQUAL(bigint, varchar) not registered". However, the json returned from `/v1/query/` doesn't include the line number. Also, the error messages should include the line number

**Comment by martint** [comment]
A couple of comments:
- That's a semantic error. SemanticExceptions hold on to the corresponding AST node, so we should be able to add and report position information easily. We'll need to extend the AST nodes to hold on to the offset/length covered by each node.
- The message should really say something like `'=' not allowed between BIGINT and VARCHAR`
