### ISSUE TITLE
predicate incorrectly pushed below aggregate in subquery may result in wrong answers

### ISSUE THREAD

**Issue by mattsfuller** [facebook/presto#3216]
When there is an aggregate function in a subquery, it is not always semantically equivalent to push a predicate from the outer query below the aggregate within the subquery. This can cause wrong results.

For example:
SELECT * FROM (SELECT count(*) as c FROM nation) as some_table WHERE 0 IS NULL;

This query should return an empty result set. However, it returns a single column, single row with value 0.

Here is the plan that query produces:
```
presto:sf1> explain select * from (select count(*) as c from nation) T where 0 is null;
                                        Query Plan                                        
------------------------------------------------------------------------------------------
 - Output[c] => [count:bigint]                                                            
         c := count                                                                       
     - Aggregate(FINAL) => [count:bigint]                                                 
             count := "count"("count_7")                                                  
         - Exchange[GATHER] => count_7:bigint                                             
             - Aggregate(PARTIAL) => [count_7:bigint]                                     
                     count_7 := "count"(*)                                                
                 - Filter[false] => []                                                    
                     - TableScan[tpch:tpch:nation:sf1.0, original constraint=false] => [] 
```

You'll see the predicate is below the aggregate. Such aggregate returns a single row, single column with value 0 when input is empty. However, the filter should applied after the aggregate in order to get the correct empty set result.

**Comment by martint** [comment]
This should be fixed in 0.108 (https://github.com/facebook/presto/pull/3132). What version did you test?

**Comment by mattsfuller** [comment]
oh. I did not test the latest. We are on 0.101. I'll close.
This one was also failing which I suspect was related:
```
SELECT COUNT(*) FROM nation HAVING log(10, 10) > 0 AND 1=2
```

**Comment by electrum** [comment]
That linked PR is empty. Commit is e370c89bd4e0859a23dcb3ff9d8bd22030c5eb07

**Comment by electrum** [comment]
@mattsfuller How did you find this one?
