### ISSUE TITLE
Can columns of a table be dynamic in Presto ?

### ISSUE THREAD

**Issue by sumanth232** [facebook/presto#3221]
Does Presto support dynamic columns in Tables, (for example, data stores which contain JSON documents, where new properties can be added in a JSON doc residing in an index/type) ?
In the Example connector, all the columns are hardcoded in 'example-metadata.json'. what if new columns are added in the csv doc ? How to handle these newly added columns in the csv (or new properties in JSON docs in elasticsearch indices) without restarting the Presto server every time a new column is added in a table ? Can this be handled by Presto at all ? Any suggestions will be of great help.
Thanks.

**Comment by sumanth232** [comment]
What is the efficient way to return the current set of columns ?
 For eg: if the data store contains JSON documents, and each JSON property is a column in the table, is it not very time consuming, to search all the docs for finding all the properties (columns) ?

As this method 'ConnectorMetadata.listTableColumns()' is called for every query, can this time consuming search be done to return the set of columns.
Does any other connector do this dynamic listing of columns ? If yes, can anybody tell me, how they do it efficiently ?

**Comment by petroav** [comment]
Sumanth -- I believe this was discussed on the mailing list so if you're satisfied with the suggestions given from the other other members could you go ahead and close this?

**Comment by mcuelenaere** [comment]
For reference, the discussion being referred to is https://groups.google.com/forum/#!searchin/presto-users/dynamic$20columns/presto-users/8jJwgAEJ5U0/TBu7JfDUHpEJ
