### ISSUE TITLE
SELECT COUNT(*) FROM table_name is very slow for elasticsearch connector

### ISSUE THREAD

**Issue by sumanth232** [facebook/presto#3239]
I have written an elasticsearch connector and used it to fetch around 1.2 million rows from an index.
The time taken to run this query is varying from 13 seconds to around 120 seconds.
I have ran it on my Mac laptop (1 node)
```
Mac configuration
Processor : 2.4 GHz Intel Core i7
Memory    : 8 GB 1600 MHz DDR3
```

I have used scan and scroll to retrieve the rows but still, it is very slow.
What are the ways to make it faster ?

**Comment by cberner** [comment]
Please keep questions to a single thread. You asked this same one on the mailing list.

**Comment by ebuildy** [comment]
@sumanth232 it depends on your ES cluster topology and connector. Is your connector scroll in parallel each index shards? Don't except low-latency with an HTTP connector.

**Comment by WangHaoCN** [comment]
Is the problem solved now? We are faced with the same problem now.
we have 4 nodes and eache node has a hardware with 24 core CPU and  128G memory;
when we try to query the data (about 25 million / 3G) , it took 150 seconds.
