### ISSUE TITLE
Support for concat that accepts more than 2 input arguments.

### ISSUE THREAD

**Issue by sopel39** [facebook/presto#3246]
Presto supports only concat(str1, str2) -> str3 while other database systems allow more than 2 arguments. Important for TPC-DS. Also concat() is part of ODBC standard.

**Comment by sopel39** [comment]
I would like to work on this one. Do you guys have any comments/hints?

**Comment by cberner** [comment]
Yep, take a look at the way `Greatest.java` works. You'll need to make `concat` into a var args function

**Comment by haozhun** [comment]
Take a look at `ArrayConstructor` class. Be aware that presto execution engine does not really provide vararg support. At plan time, vararg is implemented by calling `specialize` with a list of types (at which time number of arguments is known) and generating the appropriate implementation with the given number of arguments.

**Comment by sopel39** [comment]
Thanks, I will base the patch on ParametricScalar interface as you noted.

**Comment by martint** [comment]
Code already merged
