### ISSUE TITLE
Copy Raptor shards to backup in background thread

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3271]
Shards should be copied to the backup store in the background, allowing the writers to continue with new shards, but allowing the backup writes to be spread throughout the entire write operation. The `PageSink.commit()` should wait for the backup copies to succeed before returning.

**Comment by electrum** [comment]
This feature will fix large `DELETE` queries that currently fail because every work is writing (rather than being limited to the number of writers).

**Comment by nileema** [comment]
Working on this.
