### ISSUE TITLE
Add geometric mean aggregation function

### ISSUE THREAD

**Issue by martint** [facebook/presto#3315]

**Comment by dain** [comment]
In SQL you can get geometric mean with `exp(avg(ln(x)))`

**Comment by zinking** [comment]
@dain , isn't that going to cost much more computation effort ?

**Comment by zinking** [comment]
@martint, I took a try, the problem I found is I cannot set the initial state of the accumulator, which is currently 0 all the time. current thoughts is to create some special accumulator state for the aggregation but that seems make this issue much more complicated. 

any hints on implementing using a shortcut?

**Comment by haozhun** [comment]
Fixed by #3366.
