### ISSUE TITLE
master does not build

### ISSUE THREAD

**Issue by christophsturm** [facebook/presto#3343]
mvn clean install gives me this:

<pre>
[INFO] 4 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/christoph/Projects/collmedia/presto/presto-main/src/main/java/com/facebook/presto/operator/WindowOperator.java:[101,29] method map in interface java.util.stream.Stream<T> cannot be applied to given types;
  required: java.util.function.Function<? super java.lang.Integer,? extends R>
  found: sourceTypes::get
  reason: cannot infer type-variable(s) R
    (argument mismatch; java.util.function.Function<capture#1 of ? super java.lang.Integer,capture#2 of ? extends capture#3 of ? extends com.facebook.presto.spi.type.Type> cannot be converted to java.util.function.Function<? super java.lang.Integer,? extends capture#3 of ? extends com.facebook.presto.spi.type.Type>)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] presto-root ........................................ SUCCESS [  2.469 s]
[INFO] presto-spi ......................................... SUCCESS [  6.101 s]
[INFO] presto-jmx ......................................... SUCCESS [  2.114 s]
[INFO] presto-client ...................................... SUCCESS [  1.423 s]
[INFO] presto-parser ...................................... SUCCESS [  4.650 s]
[INFO] presto-tpch ........................................ SUCCESS [  0.981 s]
[INFO] presto-main ........................................ FAILURE [ 11.107 s]
[INFO] presto-tests ....................................... SKIPPED
[INFO] presto-kafka ....................................... SKIPPED
[INFO] presto-cassandra ................................... SKIPPED
[INFO] presto-blackhole ................................... SKIPPED
[INFO] presto-orc ......................................... SKIPPED
[INFO] presto-benchmark ................................... SKIPPED
[INFO] presto-hive ........................................ SKIPPED
[INFO] presto-hive-hadoop1 ................................ SKIPPED
[INFO] presto-hive-hadoop2 ................................ SKIPPED
[INFO] presto-hive-cdh4 ................................... SKIPPED
[INFO] presto-hive-cdh5 ................................... SKIPPED
[INFO] presto-teradata-functions .......................... SKIPPED
[INFO] presto-example-http ................................ SKIPPED
[INFO] presto-raptor ...................................... SKIPPED
[INFO] presto-base-jdbc ................................... SKIPPED
[INFO] presto-mysql ....................................... SKIPPED
[INFO] presto-postgresql .................................. SKIPPED
[INFO] presto-ml .......................................... SKIPPED
[INFO] presto-jdbc ........................................ SKIPPED
[INFO] presto-cli ......................................... SKIPPED
[INFO] presto-benchmark-driver ............................ SKIPPED
[INFO] presto-server ...................................... SKIPPED
[INFO] presto-server-rpm .................................. SKIPPED
[INFO] presto-docs ........................................ SKIPPED
[INFO] presto-verifier .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.731 s
[INFO] Finished at: 2015-07-24T12:34:09+02:00
[INFO] Final Memory: 146M/544M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project presto-main: Compilation failure
[ERROR] /Users/christoph/Projects/collmedia/presto/presto-main/src/main/java/com/facebook/presto/operator/WindowOperator.java:[101,29] method map in interface java.util.stream.Stream<T> cannot be applied to given types;
[ERROR] required: java.util.function.Function<? super java.lang.Integer,? extends R>
[ERROR] found: sourceTypes::get
[ERROR] reason: cannot infer type-variable(s) R
[ERROR] (argument mismatch; java.util.function.Function<capture#1 of ? super java.lang.Integer,capture#2 of ? extends capture#3 of ? extends com.facebook.presto.spi.type.Type> cannot be converted to java.util.function.Function<? super java.lang.Integer,? extends capture#3 of ? extends com.facebook.presto.spi.type.Type>)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :presto-main
</pre>

**Comment by cawallin** [comment]
@christophsturm -- I tried this on master, and the build passed. What compiler are you using? And what's your Java version?

**Comment by christophsturm** [comment]
<pre>
~/Projects/collmedia/presto% mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_11, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11", arch: "x86_64", family: "mac"
</pre>

**Comment by cawallin** [comment]
It's recommended that you use Java 1.8.0_40 or higher for Presto, since it has some necessary bug fixes.

**Comment by christophsturm** [comment]
thanks. it does indeed work with _45. maybe something to put in the readme, which only says java8

**Comment by cawallin** [comment]
will do, glad that fixed your problem!

**Comment by electrum** [comment]
I created #3353 to use the Maven Enforcer plugin to enforce the required update version.

**Comment by sumitkulkarni** [comment]
It's giving me this Error please help me
[INFO] 
[INFO] --- presto-maven-plugin:0.1.5:generate-service-descriptor (default-generate-service-descriptor) @ presto-jmx ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] presto-root ........................................ SUCCESS [  4.280 s]
[INFO] presto-spi ......................................... SUCCESS [  9.026 s]
[INFO] presto-client ...................................... SUCCESS [  2.954 s]
[INFO] presto-parser ...................................... SUCCESS [  6.050 s]
[INFO] presto-tpch ........................................ SUCCESS [  2.569 s]
[INFO] presto-main ........................................ SUCCESS [ 35.868 s]
[INFO] presto-jmx ......................................... FAILURE [  4.249 s]
[INFO] presto-record-decoder .............................. SKIPPED
[INFO] presto-tests ....................................... SKIPPED
[INFO] presto-kafka ....................................... SKIPPED
[INFO] presto-redis ....................................... SKIPPED
[INFO] presto-cassandra ................................... SKIPPED
[INFO] presto-blackhole ................................... SKIPPED
[INFO] presto-orc ......................................... SKIPPED
[INFO] presto-benchmark ................................... SKIPPED
[INFO] presto-hive ........................................ SKIPPED
[INFO] presto-hive-hadoop1 ................................ SKIPPED
[INFO] presto-hive-hadoop2 ................................ SKIPPED
[INFO] presto-hive-cdh4 ................................... SKIPPED
[INFO] presto-hive-cdh5 ................................... SKIPPED
[INFO] presto-teradata-functions .......................... SKIPPED
[INFO] presto-example-http ................................ SKIPPED
[INFO] presto-raptor ...................................... SKIPPED
[INFO] presto-base-jdbc ................................... SKIPPED
[INFO] presto-mysql ....................................... SKIPPED
[INFO] presto-postgresql .................................. SKIPPED
[INFO] presto-ml .......................................... SKIPPED
[INFO] presto-jdbc ........................................ SKIPPED
[INFO] presto-cli ......................................... SKIPPED
[INFO] presto-benchmark-driver ............................ SKIPPED
[INFO] presto-server ...................................... SKIPPED
[INFO] presto-server-rpm .................................. SKIPPED
[INFO] presto-docs ........................................ SKIPPED
[INFO] presto-verifier .................................... SKIPPED
[INFO] presto-testing-server-launcher ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2015-11-03T18:39:15+05:30
[INFO] Final Memory: 151M/485M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.takari.maven.plugins:presto-maven-plugin:0.1.5:generate-service-descriptor (default-generate-service-descriptor) on project presto-jmx: Execution default-generate-service-descriptor of goal io.takari.maven.plugins:presto-maven-plugin:0.1.5:generate-service-descriptor failed: A required class was missing while executing io.takari.maven.plugins:presto-maven-plugin:0.1.5:generate-service-descriptor: com\facebook\presto\connector\jmx\JmxColumnHandle (wrong name: com/facebook/presto/connector/jmx/JmxColumnHandle)
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.takari.maven.plugins:presto-maven-plugin:0.1.5
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Sumit/.m2/repository/io/takari/maven/plugins/presto-maven-plugin/0.1.5/presto-maven-plugin-0.1.5.jar
[ERROR] urls[1] = file:/C:/Users/Sumit/.m2/repository/org/apache/xbean/xbean-finder-shaded/3.18/xbean-finder-shaded-3.18.jar
[ERROR] urls[2] = file:/C:/Users/Sumit/.m2/repository/org/apache/xbean/xbean-asm5-shaded/3.18/xbean-asm5-shaded-3.18.jar
[ERROR] urls[3] = file:/C:/Users/Sumit/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar
[ERROR] urls[4] = file:/C:/Users/Sumit/.m2/repository/com/facebook/presto/presto-spi/0.74/presto-spi-0.74.jar
[ERROR] urls[5] = file:/C:/Users/Sumit/.m2/repository/io/airlift/slice/0.7/slice-0.7.jar
[ERROR] urls[6] = file:/C:/Users/Sumit/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.1.4/jackson-annotations-2.1.4.jar
[ERROR] urls[7] = file:/C:/Users/Sumit/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.1.4/jackson-databind-2.1.4.jar
[ERROR] urls[8] = file:/C:/Users/Sumit/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.1.4/jackson-core-2.1.4.jar
[ERROR] urls[9] = file:/C:/Users/Sumit/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.facebook.presto:presto-root:0.125-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :presto-jmx

**Comment by petroav** [comment]
@sumitkulkarni, judging from the file names it seems like you're building on Windows and I'm not sure Presto can build on Windows. Can you do a `mvn -V` and paste the output?
