### ISSUE TITLE
Bug!!! Hive metastore cache

### ISSUE THREAD

**Issue by lvxin1986** [facebook/presto#3356]
Hello:
Presto,I found a bug in the presto when using hive connector,as follows:
### Step1:I create table in hive
hive> use orc;
OK
Time taken: 0.372 seconds
hive> create table testt1 (c1 int, c2 String);
OK
Time taken: 2.426 seconds
hive> show tables;                            
OK
customer
lineitem
lineitem2
nation
orders
part
partsupp
region
supplier
testt1
Time taken: 0.014 seconds, Fetched: 10 row(s)
### Step2:I can see the table created in the hive through presto-cli
presto:orc> show tables;
   Table   
-----------
 customer  
 lineitem  
 lineitem2 
 nation    
 orders    
 part      
 partsupp  
 region    
 supplier  
 testt1    
(10 rows)
### Step3:I drop the table :testt1 in the hive
hive> drop table testt1;
Moved: 'hdfs://ns1/user/openuser/orc.db/testt1' to trash at: hdfs://ns1/user/hadp/.Trash/Current
OK
Time taken: 0.428 seconds
### Step4:when  I run show tables in presto，it's OK
presto:orc> show tables;
   Table   
-----------
 customer  
 lineitem  
 lineitem2 
 nation    
 orders    
 part      
 partsupp  
 region    
 supplier  
(9 rows)
### step5:but i can run the desc query!!!
presto:orc> desc testt1;
 Column |  Type   | Null | Partition Key | Comment 
--------+---------+------+---------------+---------
 c1     | bigint  | true | false         |         
 c2     | varchar | true | false         |         
(2 rows)

presto:orc> select * from testt1;

Query 20150727_084706_00034_zspvb, FAILED, 1 node
Splits: 1 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

### step6: I can not query the content of the table testt1;
presto:orc> select * from testt1;
Query 20150727_084706_00034_zspvb failed: Partition location does not exist: hdfs://ns1/user/openuser/orc.db/testt1

### step7: I can not drop the table in the presto
presto:orc> drop table testt1;
Query 20150727_091532_00042_zspvb failed: Table 'orc.testt1' not found

### step8: i can not create the table named testt1 forever!!!

presto:orc> create table testt1(c1 int,c2 varchar);
Query 20150727_084739_00036_zspvb failed: Table 'hive.orc.testt1' already exists

# I think this is a bug in presto!

**Comment by electrum** [comment]
Thanks for reporting this. The problem is that the background refresh does not work when a table has been dropped (negative responses are not cached). For now, you can lower the cache time by setting `hive.metastore-cache-ttl=1m` which will cause the entry to expire in one minute. See issue #1540.
