### ISSUE TITLE
presto job hang when large data on csv hive table.

### ISSUE THREAD

**Issue by tonywutao** [facebook/presto#3390]
hi, guys

I am testing presto for PRD usage. I encountered a presto job hang problem.

environment
* Centos 6.5
* Oracle jdk1.8_51
* prest0 0.112
* CDH5.4.0 (Hadoop-2.6.0-cdh, Hive-1.1-cdh)
* 1 node as coordinator, and other 15 as worker. 16GB Heapsize for both coordinator and worker

we have a hive (CTRL A split  File) table 40+GB  per day with partition
```shell
[ttt@server ~]$ hadoop fs -du -s -h /user/ddd/traffic/page/dt=20150730
47.0 G  141.0 G  /user/ddd/traffic/page/dt=20150730
[ttt@server ~]$ hadoop fs -du -s -h /user/ddd/traffic/page/dt=20150729
46.2 G  138.7 G  /user/ddd/traffic/page/dt=20150729
```
case1: this sql on one day partition data works good. it costed 35 seconds.
```shell
presto:mars> select c_ip, cs_uri_stem, cs_host, count(cs_uri_stem) ct, cs_method, sc_status, count( distinct x_session_id) sessioncount from traffic_page where dt='20150730' and lower(cs_host) like 'secure%' and c_ip<>'' and c_ip <> '204.14.213.149' group by c_ip, cs_uri_stem,cs_host,cs_method,sc_status having count(cs_uri_stem)>500 order by ct desc limit 1000;

Query 20150731_222950_00004_uiau7, FINISHED, 16 nodes
Splits: 305 total, 305 done (100.00%)
0:35 [84.4M rows, 47GB] [2.41M rows/s, 1.35GB/s]
```

case 2: this sql on 2-3 or more days data will hang. costed over 7 minutes, then i aborted it
```shell
presto:mars> select c_ip, cs_uri_stem, cs_host, count(cs_uri_stem) ct, cs_method, sc_status, count( distinct x_session_id) sessioncount from traffic_page where ( dt='20150730' or dt='20150729' ) and lower(cs_host) like 'secure%' and c_ip<>'' and c_ip <> '204.14.213.149' group by c_ip, cs_uri_stem,cs_host,cs_method,sc_status having count(cs_uri_stem)>500 order by ct desc limit 1000;

Query 20150731_223141_00006_uiau7, RUNNING, 16 nodes
Splits: 593 total, 576 done (97.13%)
7:31 [170M rows, 93.2GB] [378K rows/s, 212MB/s]

Query aborted by user
```

I opened the Jmx to watch the system/jvm metrics, i found when the presto job hang, cpu/network is really low, memory is no problem. i just saw the splitRunner are waiting when job hang. 
![work-bad](https://cloud.githubusercontent.com/assets/672649/9019964/4fb12b00-37ab-11e5-9f98-aada03d3f109.PNG)
![work-good](https://cloud.githubusercontent.com/assets/672649/9019963/4fafbfcc-37ab-11e5-8c4a-bb0bf296efe3.PNG)

so when the data size are too large, the splitRunner will hang?

any suggestion? Thanks in advance

**Comment by tonywutao** [comment]
fixed by this setting for worker
task.max-memory=4GB

**Comment by petroav** [comment]
@tonywutao glad you fixed the problem. Do you mind closing the issue if it's been resolved?
