### ISSUE TITLE
when the Presto will supports SQLServer connector?

### ISSUE THREAD

**Issue by ricdong** [facebook/presto#3416]
is there any plan to add a plugin for Sqlserver connector in Presto?

**Comment by haozhun** [comment]
https://groups.google.com/forum/#!searchin/presto-users/sqlserver/presto-users/RG5Cvi-b7n0/3trCM1cDZCUJ

**Comment by ricdong** [comment]
thanks, I have a try on JD-Presto, but it was compiled with presto 0.107 since we use high version. https://github.com/CHINA-JD/presto/issues/1

**Comment by petroav** [comment]
@ricdong if this is resolved, can you please close the issue? Thanks!

**Comment by lotuc** [comment]
I just create a new repo [lotuc/presto-sqlserver](https://github.com/lotuc/presto-sqlserver) and separate the sqlserver connector in case someone need it.

**Comment by sajeevpr** [comment]
will this connector work with AD authentication?
