### ISSUE TITLE
Presto Truck Factor

### ISSUE THREAD

**Issue by gavelino** [facebook/presto#3421]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Presto** and obtained a value of **2**.

The developers responsible for this TF are:

Dain Sundstrom - author of 49% of the files
David Phillips - author of 31% of the files

To validate our results, we would like to ask **Presto** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Presto**?

(b) Do you agree that **Presto** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Presto** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by martint** [comment]
No, number of files written or touched by a given developer are not a good measure of whether they are more "important" than others to the project. There is a lot of shared knowledge in the team (as a result of design discussions, code reviews, etc.) that are not captured by those metrics.
