### ISSUE TITLE
Question about Presto non-interactive mode job submission/remote job submission

### ISSUE THREAD

**Issue by liusztc09** [facebook/presto#3430]
Hi Presto experts,

Is there a way to submit Presto query remotely via HTTP instead of using interactive mode. What format should I follow or commands I should use? Thanks a lot!

Best,
David

**Comment by KBP-TDC** [comment]
How about using JDBC driver?

**Comment by liusztc09** [comment]
Hi @KBP-TDC , thanks for the reply! I've succeeded in both JDBC and ODBC, but I was wondering whether there is a way to submit a script as a file or via http request? Does presto provide these features or I need to build my own?

**Comment by nezihyigitbasi** [comment]
JDBC driver uses Presto's REST interface and does an HTTP POST with the sql query and then a bunch of GETs to get each page of the result set. You can start with [this](https://gist.github.com/electrum/7710544).

**Comment by liusztc09** [comment]
@nezihyigitbasi Thanks a lot for the advice!

**Comment by electrum** [comment]
There are drivers / client libraries for many languages: https://prestodb.io/resources.html

I recommend using one of them and if it doesn't fit your needs, please send feedback or a patch to the author of the library.

**Comment by liusztc09** [comment]
@electrum Thanks a lot David

**Comment by petroav** [comment]
@liusztc09 if you consider the issue resolved can you please go ahead and close it? Thanks!
