### ISSUE TITLE
presto db uses hive table index?

### ISSUE THREAD

**Issue by zhuqunzhou** [facebook/presto#3433]
I have hive table with RC file format and index is created on one the column of the table to improve performance of the query with WHERE clause. 
        My question is that whether presto engine will use hive table’s index if column in WHERE clause is indexed column?

**Comment by albertoRamon** [comment]
Hello

any solution to this ??

prestoDB use Hive's Indexes ?

**Comment by dain** [comment]
Presto currently does not understand Hive indexes.

**Comment by albertoRamon** [comment]
a lot of thanks ¡¡

have a nice weekend

2015-10-23 19:44 GMT+02:00 Dain Sundstrom <notifications@github.com>:

**Comment by mgalushka** [comment]
Hi,

Are there any plans in roadmap to support Hive indexes or any other indexing plans to speedup queries?

**Comment by albertoRamon** [comment]
I think no, see [this](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/orc/OrcPageSource.java):

only check if is a partition column, 
` for (int columnIndex = 0; columnIndex < columns.size(); columnIndex++) {`
`if (column.isPartitionKey()) {`

(currently I'm not using PrestoDB, I'm following changes for future application uses)
