### ISSUE TITLE
-XX:OnOutOfMemoryError=kill -9 %p doesn't work

### ISSUE THREAD

**Issue by xerial** [facebook/presto#3441]
When OutOfMemoryError happens (probably caused by this untracked memory usage https://github.com/facebook/presto/pull/3414), JVM option `-XX:OnOutOfMemoryError=kill -9 %p` doesn't  work and presto worker process becomes unstable (i.e., the process looks like working, but actually cannot process any task request because Jetty enters a strange state)

This is probably caused by a bug of JVM https://bugs.openjdk.java.net/browse/JDK-8027434. JVM cannot create a new process to run `kill -9` upon OOM.

If the presto worker dies properly, there should be many workarounds. For example, retrying the query from the scratch or launch a new presto worker process. But the problem is presto worker that hits OutOfMemory error continues to run and shows strange behaviors. 

Here an excerpt of the log messages when OOM occurred:
https://gist.github.com/xerial/ffab9b4b195e277dbade

Do you have any similar problem? If so, how do you handle it? 

Thanks in advance.

**Comment by cawallin** [comment]
I believe that Facebook uses the jvmkill agent: https://github.com/airlift/jvmkill.

**Comment by martint** [comment]
Yup, that's exactly how we deal with this issue and the reason we wrote the jvmkill agent.

**Comment by xerial** [comment]
Nice solution! This problem has been a headache for us. 
I'll try it.
