### ISSUE TITLE
Why the test instances in TestAnalyzer.java can't be run successfully?

### ISSUE THREAD

**Issue by jiugelicun** [facebook/presto#3469]
I want to do some modifications on the Presto code.
I suffer some errors when running com.facebook.presto.sql.analyzer.TestAnalyzer.testInsert (and the other testing instances have the same problem)

The error information is like this:
java.lang.UnsupportedOperationException: not yet implemented
	at com.facebook.presto.sql.parser.AstBuilder.aggregateResult(AstBuilder.java:1036)
	at com.facebook.presto.sql.parser.AstBuilder.aggregateResult(AstBuilder.java:124)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:71)
	at org.antlr.v4.runtime.RuleContext.accept(RuleContext.java:183)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at org.antlr.v4.runtime.RuleContext.accept(RuleContext.java:183)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:104)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:66)
	at com.facebook.presto.sql.analyzer.TestAnalyzer.analyze(TestAnalyzer.java:852)
	at com.facebook.presto.sql.analyzer.TestAnalyzer.testInsert(TestAnalyzer.java:499)

then I debug the source code in AbstractParseTreeVisitor.java 
 public T visitChildren(RuleNode node) {
   T result = defaultResult();
   int n = node.getChildCount();
   for (int i=0; i<n; i++) {
      if (!shouldVisitNextChild(node, result)) {
         break;
      }

      ParseTree c = node.getChild(i);
      T childResult = c.accept(this);
      result = aggregateResult(result, childResult);
   }

   return result;
}
and AstBuilder.java:
@Override
protected Node aggregateResult(Node aggregate, Node nextResult)
{
    if (nextResult == null) {
        throw new UnsupportedOperationException("not yet implemented");
    }

    if (aggregate == null) {
        return nextResult;
    }

    throw new UnsupportedOperationException("not yet implemented");
}
I find that result and childResult are both null if c is a leaf node. So the program throws an exception, UnsupportedOperationException("not yet implemented");

So,  is there anything wrong with my operation? And how to test the code after modified?

**Comment by electrum** [comment]
Can you post a patch with your changes?

**Comment by jiugelicun** [comment]
I didn't make any changes, I ran the source code downloaded directly.
I want to run the test instance successfully first, then modify the code, and test again.
But, the original  test instance can't be run successfully .

**Comment by joy-yao** [comment]
Did you do 'mvn clean install' first before you run the test?

**Comment by jiugelicun** [comment]
hi joy-yao, thank you for your reply!
I did resolve the maven dependencies first.
But the project lacks several files: SqlBaseBaseListener.java, SqlBaseLexer.java, SqlBaseListener.java and SqlBaseParser.java. I used shell command "antlr4 SqlBase.g4" to generate the 4 files, and then copied them to the package "com.facebook.presto.sql.parser" .
Besides, SqlBaseBaseVisitor.java and SqlBaseVisitor.java are both needed and not included in the original project, I downloaded them from "http://grepcode.com/file/repo1.maven.org/maven2/com.facebook.presto/presto-parser/0.107/com/facebook/presto/sql/parser/SqlBaseVisitor.java/", then copied them to the package "com.facebook.presto.sql.parser"

then I built the project successfully,but encountered the error above when running the test instances.

**Comment by electrum** [comment]
The ANTLR sources need to be generated from Maven. You can run `mvn clean install` to do a full building including all the tests (can take 10+ minutes), or do `mvn clean install -DskipTests` to do a full build without tests. If you are working on the parser and want to just build it, do `mvn clean install -pl presto-parser`.

**Comment by electrum** [comment]
Do not try to generate the sources manually with the ANTLR command or copy them from anywhere else. As you have found, that will not work :)

**Comment by electrum** [comment]
Please reopen this issue if you need further assistance.

**Comment by hustnn** [comment]
Hi, @electrum . Can I know why cannot use ANTLR command to generate those sources?
