### ISSUE TITLE
Support to OR'ed predicates in tupleDomain 

### ISSUE THREAD

**Issue by puneetjaiswal** [facebook/presto#3471]
Quoting @electrum 's comment in this post https://groups.google.com/forum/#!searchin/presto-users/david/presto-users/gw63DLA86BU/naVRaK6m2uEJ

"Unfortunately, it is not yet possible to pass an OR expression into a connector with the current connector interface. We do plan to support passing arbitrary expressions (and even full queries) into connectors."

There has been some changes around TableLayout and ConnectorPartition. Does presto support predicate pushdown for OR filters in tuple domain yet? 

This is significantly important when you need to run a query like (SELECT * FROM foo WHERE foo.id IN  (x, y,z .....)) against huge amount of data. Currently presto fetches entire data in cluster to run this kind of queries which is impractical.

Creating this issue to track development around this.

Thanks.

**Comment by puneetjaiswal** [comment]
Closing this.. as I can see OR filters as well in the tuple domain.

**Comment by electrum** [comment]
To clarify, we support this:

    (a = 1 OR a = 2) AND (b = 3 OR b = 4)

Which is the same as this:

    a IN (1, 2) AND b IN (3, 4)

But not this:

    a = 1 OR b = 2

**Comment by puneetjaiswal** [comment]
Thanks for replying so quick @electrum 
Do you guys have plan to support the last type of filters [ `a = 1 OR b = 2` ] ?

**Comment by dain** [comment]
A tuple domain for `a = 1 OR b = 2` is not possible (it only supports `AND` between different columns).  This will be supported when we have push down for arbitrary expressions to connectors.
