### ISSUE TITLE
PrestoDB is very slow

### ISSUE THREAD

**Issue by grepwood** [facebook/presto#3480]
I have Presto connected to at least 10 databases and a few of them perform badly.

There's 2275 rows and I get them via PrestoDB in 6 minutes, but through a native MySQL client I get them in 0.71 seconds. All through the same network connection.

Why is Presto so slow?

**Comment by KBP-TDC** [comment]
We are investigating this issue and discussing on IRC, will update later with the findings.

**Comment by martint** [comment]
@KBP-TDC any updates?

**Comment by KBP-TDC** [comment]
I believe the problem was solved by moving Presto to the same data center as the MySQL instance (or the other way around). @grepwood could you please confirm so that we can close this ticket?

**Comment by grepwood** [comment]
@KBP-TDC We haven't done that. Instead, my manager wrote an optimized SQL connector for Presto and it's doing alright.

**Comment by petroav** [comment]
@grepwood it sounds like you found a solution, can you close the ticket when you get a chance?

**Comment by KBP-TDC** [comment]
@grepwood : if you care to share what / how did you optimize the connector, it might be useful for the community.
