### ISSUE TITLE
Create P4HyperLogLog type

### ISSUE THREAD

**Issue by erichwang** [facebook/presto#3481]
Our current HyperLogLog type (from airlift implementation) is a dynamic implementation that switches between a sparse HLL and and a dense HLL depending on which one saves more memory. However, the each have different performance and accuracy characteristics.

We should create a new Presto type called P4HyperLogLog that starts and stays strictly as the dense HLL.
- P4HyperLogLog should implicitly cast to HyperLogLog
- HyperLogLog can be explicitly casted to P4HyperLogLog

**Comment by yangyangyyy** [comment]
I'll be working on this

**Comment by yangyangyyy** [comment]
Eric:

we are planning to keep this new class in presto package or airlift.stats.cardinality package ?

 when you say "should implicitly cast to Hll ", does that mean P4Hll derives Hll ? but then Hll's only constructor takes an HllInstance as param,  and HllInstance is package accessible, so the new class has to be in airlift package?

thanks
Yang

**Comment by yangyangyyy** [comment]
I'm reading the background knowledge about HyperLogLog and LogLog algo in https://en.wikipedia.org/wiki/Flajolet%E2%80%93Martin_algorithm

**Comment by yangyangyyy** [comment]
unfortunately the wiki https://en.wikipedia.org/wiki/Flajolet%E2%80%93Martin_algorithm actually describes the algorithm wrong. it says step 3 is choosing the smallest index, but according to the original paper and http://blog.notdot.net/2012/09/Dam-Cool-Algorithms-Cardinality-Estimation it should be taking the largest. I edited the wiki to correct version
