### ISSUE TITLE
more splites more fast?

### ISSUE THREAD

**Issue by zhuqunzhou** [facebook/presto#3571]
if i set the size of splite lower,presto will splite more number,and the speed of query change faster.(read data from hive)

**Comment by cberner** [comment]
Yep. If you're querying a small amount of data then reducing the size of the splits can help you achieve increased parallelism. The recommended way of doing this is via `hive.max-initial-splits` and `hive.max-initial-split-size` this way only the first N splits will have a small size and if you run a query over a larger amount of data the split size will be larger again (which keeps overhead low).

Let us know if you have more questions!

**Comment by zhuqunzhou** [comment]
@cberner  ：
    If I set up  `hive.max-split-size ` and  ` hive.max-initial-split-size`  and `hive.max-initial-splits ` , presto will be how to deal with the query ? If my server is configured well, it is not the  `hive.max-split-size ` set to be smaller and faster.

Thank you very much.

**Comment by cberner** [comment]
The first N (where N = `hive.max-initial-splits`) will use size `hive.max-initial-split-size`. After that `hive.max-split-size` will be used
