### ISSUE TITLE
Implement max_by and min_by with an additional `n` parameter

### ISSUE THREAD

**Issue by haozhun** [facebook/presto#3620]
#3261 added support for `n` parameter to `max` and `min` functions. We also want `n` parameter for `max_by` and `min_by` functions.

* Your implementation will need to extend `TypedHeap` to allow additional data for heap elements. (maybe subclass TypedHeap?)
* Your implementation will also add `AbstractMinMaxByNAggregation` which should be similar to `AbstractMinMaxNAggregation`.
* Your implementation shouldn't use `getSingleValueBlock`

**Comment by raghavsethi** [comment]
Claiming this.

**Comment by raghavsethi** [comment]
Pushed.
