### ISSUE TITLE
"Entering secondary queue failed" when greater than maxQueued queries enter queue for which they have slots reserved

### ISSUE THREAD

**Issue by sopel39** [facebook/presto#3637]
Consider queues:

```
    "user.${USER}": {
      "maxConcurrent": 2,
      "maxQueued": 2
    },
    "dashboard.${USER}": {
      "maxConcurrent": 1,
      "maxQueued": 1
    },
```

Then we start two queries at the same time. Two slots will be reserved in `dashboard.${USER}` queue. Due to the current implementation of the queues, the queries will first be enqueued in the `dashboard.${USER}` (even though one of them could be immediately started). In this case, `queryQueueSize` will be 2 and greater than `maxQueued`. This will cause `Entering secondary queue failed` error to be thrown (`com.facebook.presto.execution.QueuedExecution.start(QueuedExecution.java:74`).

To reproduce this issue on your machine, comment out line nr 56 (waiting for the first query to start) in  `testSqlQueryQueueManager` and run the test.

FYI: @cberner @electrum @kokosing

**Comment by kokosing** [comment]
I will try to solve this issue.
