### ISSUE TITLE
Report a possible race issue

### ISSUE THREAD

**Issue by baigd** [facebook/presto#3647]
Hi, Developers of facebook/presto,

I am writing to report a race issue on use of ConcurrentHashMap. The issue is reported by our tool in an automatic way. Although manually confirmed, it would be a false positive, given we do not know the specification of the program. We would very appreciate if you could check below for details and confirm with us whether it is a real problem. For more information, please refer to our website: http://sav.sutd.edu.sg/?page_id=2845

File: facebook/presto/presto-blackhole/src/main/java/com/facebook/presto/plugin/blackhole/BlackHoleMetadata.java
Location: Line (149/150,172/136)
Description: 
The remove-then-put operations on "tables" in line 149 and 150 are guarded by the lock "tables". If the intention is to guarantee the atomicity of the remove-then-put operations, then the write operations in line 136, 172 may break this atomicity. Relying on the ConcurrentHashMap to ensure exclusive access is dangerous since ConcurrentHashMap has no guarantee of exclusive access.

**Comment by electrum** [comment]
https://github.com/facebook/presto/blob/master/presto-blackhole/src/main/java/com/facebook/presto/plugin/blackhole/BlackHoleMetadata.java

**Comment by losipiuk** [comment]
It seems to me that synchronization in BlackHoleMetadata class is not needed at all. Even if all accesses to `tables` map were done in synchronized section we could still run into race conditions on metadata access. 

To avoid that we would need add synchronization mechanisms in *Task classes (e.g. CreateTableTask) or even higher in DataDefinitionExecution.

The downside of that is that ConnectorMetadata interface would probably become much less user friendly.

**Comment by kokosing** [comment]
Simple approach of fixing that would be to try implement transaction-like
metadata storage with using ConnectorSession.getStartTime() as transaction id (txid)
Then session with higher txid would need to wait for all
operations with lower txid to finish.

What do you think about it?
