### ISSUE TITLE
not able to install package 

### ISSUE THREAD

**Issue by gupta2007vaibhav** [facebook/presto#3662]
rpm -ivh presto-server-rpm-0.120.SNAPSHOT-1.x86_64.rpm 
error: presto-server-rpm-0.120.SNAPSHOT-1.x86_64.rpm: headerRead failed: hdr load: BAD
error: presto-server-rpm-0.120.SNAPSHOT-1.x86_64.rpm cannot be installed

**Comment by cawallin** [comment]
What is the version of rpm that you're trying to use? We found a bug with redline (the pure Java RPM library we use) and contributed a fix back (https://github.com/craigwblake/redline/pull/94), but have not yet gotten that propagated through the redlinerpm-maven-plugin.

**Comment by gupta2007vaibhav** [comment]
RPM version 4.11.1

**Comment by cawallin** [comment]
You can download the redline-maven-plugin (https://github.com/spaulg/redlinerpm-maven-plugin/), update the redline version number to 1.2.2 and the redline-maven-plugin version to something higher than 1.0, compile it and install it in maven (https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html), and then change the redline-maven-plugin dependency in the pom.xml of presto-server-rpm to the new version and compile Presto.

**Comment by rschlussel** [comment]
If you specify version 1.2.2 of redline-rpm as a dependency in the pom.xml of presto-server-rpm, you should be able to directly override the redline-rpm version that redlinerpm-maven-plugin uses (see http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies).

**Comment by gupta2007vaibhav** [comment]
I did the changed to pom.xml as below.
 69                     <plugin>
 70                         <groupId>uk.co.codezen</groupId>
 71                         <artifactId>redlinerpm-maven-plugin</artifactId>
 72                         <version>1.2.2</version>
 73                         <extensions>true</extensions>

but there is no packages available for this.
[INFO] Scanning for projects...
[WARNING] The POM for uk.co.codezen:redlinerpm-maven-plugin:jar:1.2.2 is missing, no dependency information available
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.facebook.presto:presto-server-rpm:0.120-SNAPSHOT (/home/dev/presto/presto-server-rpm/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin uk.co.codezen:redlinerpm-maven-plugin:1.2.2 or one of its dependencies could not be resolved: Failure to find uk.co.codezen:redlinerpm-maven-plugin:jar:1.2.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: rpm @ com.facebook.presto:presto-server-rpm:[unknown-version], /home/dev/presto/presto-server-rpm/pom.xml, line 13, column 16
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by cawallin** [comment]
So, the redlinerpm-maven-plugin was updated (https://github.com/spaulg/redlinerpm-maven-plugin/issues/1).

It's unclear whether to update to the new plugin at this point -- since the new version of redline doesn't work for rpm < 4.6 -- but you can just change the plugin version to 1.1 for redlinerpm-maven-plugin in the pom.xml.

**Comment by gupta2007vaibhav** [comment]
Thanks a lot it works.!

**Comment by petroav** [comment]
@gupta2007vaibhav if the issue has been solved, can you go ahead and close the issue? Thanks!

**Comment by kokosing** [comment]
@martint I think you can close this issue as it seems to be solved.

**Comment by petroav** [comment]
This commit should have fixed the issue https://github.com/facebook/presto/commit/add1241b04e6c3ecc8777dfec19502c5741e903c.
