### ISSUE TITLE
How to save/export result into Hdfs in Presto shell?

### ISSUE THREAD

**Issue by ricdong** [facebook/presto#3690]
How to save the output of SQL statements to HDFS in Presto shell client ? is there any semantic like the hive `insert overwrite [local] directory '/tmp/output/...' select * ... ` ?

**Comment by martint** [comment]
The closest you can get is to create another table with your results:

```CREATE TABLE xxx AS SELECT ...```

You can export data to a local directory by invoking the CLI with `--execute` or `--file` (though, what out for https://github.com/facebook/presto/pull/3463)

We've also been considering adding a new connector that can read/write from distributed filesystems (s3, hdfs, etc) without the need for a hive metastore, but when and exactly how it'd be implemented is to be determined.

**Comment by hustnn** [comment]
@martint 

Can presto support read/write from distributed filesystems (s3, hdfs, etc) without the need for a hive metastore now?
