### ISSUE TITLE
Make the CachingHiveMetastore use the IMetaStoreClient  interface instead of directly calling the ThriftHiveMetastore client

### ISSUE THREAD

**Issue by mbeitchman** [facebook/presto#3764]
Change the CachingHiveMetastore to use the IMetaStoreClient interface instead of directly calling the ThriftHiveMetastore client. This allows for the CachingHiveMetastore implementation to use other implementations of the IMetastoreClient interface without having to change any code
in the CachingHiveMetastore implementation.

Corporate CLA completed by Amazon.

**Comment by electrum** [comment]
Is this a feature request or something you plan to work on?

**Comment by mbeitchman** [comment]
I sent the pr which you've seen.

**Comment by mbeitchman** [comment]
I will send a new pr with the approach we discussed.

**Comment by mbeitchman** [comment]
fixed https://github.com/facebook/presto/pull/3785
