### ISSUE TITLE
Allow specifying list of columns for INSERT

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3800]

**Comment by kokosing** [comment]
I can take this one.

**Comment by kokosing** [comment]
@electrum @martint 

I am working on this, currently I have added support for this to SQL parser and things around it. This was an easy part.

 As for planning and execution I am thinking about adding new plan node and operator (ColumnMappingNode and ColumnMappingOperator), this would be a step which would map query output columns into a table columns using specified columns in insert into query. I thought this is needed as columns from insert into query could be specified in any order. Also this step (operator) could generate blocks with null values for columns which were not specified in a query.

This step (plan node & operator) would be optional. Used only when column list is specified and has not all table columns or different order of columns than table has.

I am couriuos of your opinion about this approach.

**Comment by kokosing** [comment]
It seems that new operator and plan node is not needed. I think I can reuse a ProjectNode for this.

**Comment by martint** [comment]
@kokosing, using a ProjectNode is exactly how you'd do it :)

**Comment by kokosing** [comment]
@electrum It is fixed and can be closed. I had a typo in the commit so it didn't get closed automatically.
