### ISSUE TITLE
Does presto support Hive with AvroSerde

### ISSUE THREAD

**Issue by caojia** [facebook/presto#3828]
I have a hive table, created by avro schema. 

Here is an example from Hive's official document. My question is, does presto support avro serde? When I query the hive table, I got HIVE_CURSOR_ERROR error.

```
CREATE TABLE kst
  PARTITIONED BY (ds string)
  ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.avro.AvroSerDe'
  STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat'
  OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.avro.AvroContainerOutputFormat'
  TBLPROPERTIES (
    'avro.schema.url'='http://schema_provider/kst.avsc');
```

Thanks!

**Comment by dain** [comment]
We had one person asked about Avro a couple years ago, and I looked into it.  Getting the remote schema thing working was not straight forward, so I asked them if it was possible to rewrite it in another format (Avro is one of the slowest formats).  They were able to rewrite the data, and it hasn't really come up again.

**Comment by caojia** [comment]
Thanks dain. We'll look into other formats...

**Comment by pratikasarda** [comment]
Hi Guys,

We are working with Apache Hive and Avro and we're interested in to take PrestoDB included in our Production stack but current problem is that it doesn't support Avro Format. 

Can anyone let me know how can I support Avro Format in PrestoDB?

We are looking on Presto 0.130 and Apache Hive 1.x on Amazon EMR 4.

Thanks

**Comment by petroav** [comment]
This should answer your question https://groups.google.com/d/topic/presto-users/U13qRlUyWX4/discussion

And if you search the group for Avro you'll get even more info and discussion on the topic.

**Comment by pratikasarda** [comment]
Thanks for your answer. We were referring same but it wasn't working. Is there any other solution for this.

**Comment by skoppar** [comment]
There seems to be some dependency issue. Adding avro jars to the pom.xml did not generate package successfully. There seem to be some conflicts
