### ISSUE TITLE
LIKE predicate not supported as part of join clause

### ISSUE THREAD

**Issue by losipiuk** [facebook/presto#3888]
Only queries with comparison operators in JOIN clause are allowed now in Presto.

E.g. query like:
```
select customer.custkey ck, orders.orderkey ok from customer join orders on customer.custkey = orders.custkey and orders.comment like 'ala%';
```

willl fail with `Non-equi joins not supported: ("orders"."comment" LIKE 'ala%')` error.

**Comment by losipiuk** [comment]
@martint I would like to pursue this one. This is intermediate step in making TPC-H Q13 work.
Followup would be to support at least simple cases of non-equality predicates in condition for OUTER JOINS. I created #3889 issue for that.

Is anyone working on that right now. Or does it make sense for me to work on this one?

cc: @ilfrin

**Comment by martint** [comment]
We do support some limited forms of non-equi joins. I'm curious about why this form doesn't work. There's no one working on this, yet. Go for it!

**Comment by losipiuk** [comment]
fixed
