### ISSUE TITLE
Hive connector - DROP TABLE does not work

### ISSUE THREAD

**Issue by tomz** [facebook/presto#3912]
I was able to create a table in Hive but not able to delete it:

```
[hadoop@ip-10-93-197-190 ~]$ presto-cli --catalog hive --schema default
presto:default> show tables;
   Table   
-----------
 emp       
 sample_07 
 sample_08 
(3 rows)

Query 20151106_223336_00007_vpcx5, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0:00 [3 rows, 80B] [38 rows/s, 1023B/s]

presto:default> create table person(firstname varchar, lastname varchar);
CREATE TABLE
presto:default> show tables;
   Table   
-----------
 emp       
 person    
 sample_07 
 sample_08 
(4 rows)

Query 20151106_223415_00009_vpcx5, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0:00 [4 rows, 103B] [87 rows/s, 2.21KB/s]

presto:default> drop table person;
Query 20151106_223422_00010_vpcx5 failed: Access Denied: Cannot drop table default.person

presto:default> 
```

**Comment by dain** [comment]
The default security settings for hive don’t allow you do drop tables.  Set this config in the hive catalog file to enable drop table:

  hive.allow-drop-table=true

**Comment by tomz** [comment]
Thanks @dain that worked.

**Comment by dsr301** [comment]
Can you let me know the file where we need to changed this. I have changed it in hive-site.xml and i am still not able to drop hive tables from prestp

**Comment by dandu1008** [comment]
> The default security settings for hive don’t allow you do drop tables.  Set this config in the hive catalog file to enable drop table  `hive.allow-drop-table=true`
> 

Your solution works fine for 'default' schema. But it's unable to drop table from other than 'default' schema.

**Comment by taylorbentz** [comment]
I'm not sure where this file is in the file system, so I'm not sure how to edit it?

**Comment by taylorbentz** [comment]
> I'm not sure where this file is in the file system, so I'm not sure how to edit it?

And does it need to be edited on each of the cluster nodes or is there a process for doing that automatically?

**Comment by taylorbentz** [comment]
> The default security settings for hive don’t allow you do drop tables. Set this config in the hive catalog file to enable drop table `hive.allow-drop-table=true`

Can you explain how to find that file on the EMR cluster?

**Comment by beinan** [comment]
> > The default security settings for hive don’t allow you do drop tables. Set this config in the hive catalog file to enable drop table `hive.allow-drop-table=true`
> 
> Can you explain how to find that file on the EMR cluster?

If you are using EMR, the best practice would be change the json configuration file https://docs.amazonaws.cn/en_us/emr/latest/ReleaseGuide/emr-presto-considerations.html

```
{"Classification":"presto-connector-hive","Properties":{...,"hive.allow-drop-table":"true"}}
```

Or add the property to ``/etc/presto/conf/catalog/hive.properties``  (I'm not using the most recent version of emr, so the path might be not exactly the same)

**Comment by taylorbentz** [comment]
> > > The default security settings for hive don’t allow you do drop tables. Set this config in the hive catalog file to enable drop table `hive.allow-drop-table=true`
> > 
> > 
> > Can you explain how to find that file on the EMR cluster?
> 
> If you are using EMR, the best practice would be change the json configuration file https://docs.amazonaws.cn/en_us/emr/latest/ReleaseGuide/emr-presto-considerations.html
> 
> ```
> {"Classification":"presto-connector-hive","Properties":{...,"hive.allow-drop-table":"true"}}
> ```
> 
> Or add the property to `/etc/presto/conf/catalog/hive.properties` (I'm not using the most recent version of emr, so the path might be not exactly the same) You just need change it on the coordinator, no change on worker node needed.

Awesome thanks so much! That just solved a bunch of other questions I had, for some reason I thought I should be looking in hadoop directory for conf/catalog/hive.properties. 

For any other noobs out there, I had to issue the following commands to restart the presto server for these config changes to take effect:
`sudo systemctl stop presto-server`
`sudo systemctl start presto-server`
