### ISSUE TITLE
Accessing S3 data in another region fails

### ISSUE THREAD

**Issue by lloydpick** [facebook/presto#4018]
I have data in S3 buckets in us-west-2 and eu-west-1 and my cluster in us-west-2. I can't consolidate my data to one region, and need to be able to query both buckets from one cluster in one AWS region.

Hive handles these external tables fine, but once I try and query the one that isn't in the same region as the cluster through Presto I get 301 errors from S3...

    The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: ...)

After hunting through the code, I think this is due to this commit - https://github.com/facebook/presto/commit/f827a1277e26a62d43d15caf03f94abd100fc13d

Is there a way for this behaviour to be disabled?

Was running 0.126, now rolled back to version 0.117 (before that commit) and it works fine.

**Comment by nezihyigitbasi** [comment]
As far as I can see from the code I don't think there is a way to disable this behavior, maybe it's time we create a config parameter to make this behavior optional as this change is putting a location constraint (for the curious see [this](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region))

@electrum The initial PR had a config parameter `presto.s3.region`, which was also not the correct solution as it was constraining the location. I think we should define a boolean config parameter (something like pin to current region) to make this behavior optional. What do you think?

**Comment by lloydpick** [comment]
For me personally, I'd just like the way of turning off the automatic detection behaviour, as I have multiple tables in multiple regions, so being able to specify just one region won't cut it.

**Comment by electrum** [comment]
I think we should add a flag and disable it by default (revert to the old behavior that matches Hive).

**Comment by nezihyigitbasi** [comment]
OK I will create a PR for this shortly.

**Comment by electrum** [comment]
This will be fixed on 0.129
