### ISSUE TITLE
Improve performance of GROUP BY hashing

### ISSUE THREAD

**Issue by cberner** [facebook/presto#4019]
I'm not sure what the exact problem is, but when running a huge GROUP BY (1B+ groups per worker) that had a small number of rows per group I saw *very* poor performance (< 1K rows per cpu sec). Profiling showed that almost all the time is being spent in hashing:
+   82.56%  presto-facebook  perf-170.map                   [.] com_facebook_presto_$gen_PagesHashStrategy_71.positionEqualsRow

This must have been the call from `MultiChannelGroupByHash.positionEqualsCurrentRow`, since I wasn't doing a SEMI JOIN in my query.

I'd start with a benchmark that does a simple count(*) with a large number of groups, then one thing to look at is our fill ratio in `MultiChannelGroupByHash` which is set to 90% (`HashMap` uses 75%, and 90% seems pretty high to me)

**Comment by raghavsethi** [comment]
Follow-up task: #4133
