### ISSUE TITLE
Add Presto version to QueryCreatedEvent and QueryCompletionEvent

### ISSUE THREAD

**Issue by dain** [facebook/presto#4107]
We should record the Presto version in the query events so if there is a problem with a specific version, it is easy to find queries that ran with that version.

**Comment by harunurhan** [comment]
@dain, Isn't it already in these events?:

https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/event/query/QueryCreatedEvent.java#L33

https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/event/query/QueryCompletionEvent.java#L40

Or are server version and presto version different?

**Comment by dain** [comment]
LOL missed that :)
