### ISSUE TITLE
Add support for TRY()

### ISSUE THREAD

**Issue by martint** [facebook/presto#4148]
We need a more general mechanism to deal with data errors similar to how `TRY_CAST` works. In the past, we've discussed adding a special form `TRY` that can be used to wrap any expression and would return `NULL` if the expression ever throws an exception during evaluation.

For example, the following query would return a single `NULL` value:

```sql
SELECT TRY(a / b) FROM (VALUES (1, 0)) t (a,b)
```

**Comment by dain** [comment]
It would be nice to have an overloaded version where I could specify the default value.

**Comment by zinking** [comment]
@dain default value could easily be achieved by combining `coerce` or `case when`

**Comment by martint** [comment]
This is already implemented
