### ISSUE TITLE
Hive INSERT creates files with the wrong data type

### ISSUE THREAD

**Issue by electrum** [facebook/presto#4219]
Presto writes the data to the file as a `bigint` but the partition column type is `int`:

```
hive> create table if not exists test_presto_int (dummy INT, name STRING) partitioned by (ds STRING);

presto> insert into test_presto_int select 3 as dummy, 'abc' as name, '2015-12-21' as ds;

hive> describe formatted test_presto_int partition (ds='2015-12-21');
...
dummy               	int                 	None                
...

hive> select * from test_presto_int where ds='2015-12-21';
OK
Failed with exception java.io.IOException:java.lang.ClassCastException: org.apache.hadoop.io.LongWritable cannot be cast to org.apache.hadoop.io.IntWritable
Time taken: 9.664 seconds

**Comment by electrum** [comment]
A related issue is handling of values that are outside of the Hive type range. For example, if we insert something larger than MAX_INT into a Hive integer column.

**Comment by electrum** [comment]
This might also be a problem for inserting into a non-partitioned table.

**Comment by app-tarush** [comment]
Can I take this issue for fixing.

**Comment by electrum** [comment]
@app-tarush Yes. Ideally, we should support writing these types, but that is complicated and has some questions to resolve (such as out-of-range values). The immediate fix for this issue is to check the Hive types in `HiveMetadata.beginInsert()` and fail if the type does not directly map to a Presto type. So, these should not be supported: `BYTE`, `SHORT`, `INT`, `FLOAT`

**Comment by electrum** [comment]
This check also needs to be done in the `HiveRecordWriter` constructor since the partition might have a different schema.

**Comment by electrum** [comment]
Actually, a better alternative to explicitly checking in `HiveRecordWriter` is to pass in the input column types as a `HiveType` rather than a Presto `Type`.

**Comment by haozhun** [comment]
Fixed by #4466

**Comment by haozhun** [comment]
Reopen. Actually this issue is not fixed. Instead of writing corrupted data, we now have an explicit check that fails the query.

To close this issue, we should be able to write to such columns.

**Comment by electrum** [comment]
Writing broken files is fixed. We can open a new issue to track the feature (this title is incorrect for that).
