### ISSUE TITLE
Shutdown via REST seems to be ignored

### ISSUE THREAD

**Issue by RobinUS2** [facebook/presto#4221]
According to the docs of release 0.128 it is now possible to gracefully shutdown a node ( see https://prestodb.io/docs/current/release/release-0.128.html ). This however doesn't seem to work, see log below.

```
# curl -v -XPUT --data '"SHUTTING_DOWN"' -H "Content-type: application/json" "http://localhost:8888/v1/info/state" && sleep 1 && curl http://localhost:8888/v1/info/state
* About to connect() to localhost port 8888 (#0)
*   Trying ::1... connected
* Connected to localhost (::1) port 8888 (#0)
> PUT /v1/info/state HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:8888
> Accept: */*
> Content-type: application/json
> Content-Length: 15
> 
< HTTP/1.1 200 OK
< Date: Tue, 22 Dec 2015 09:03:24 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
* Closing connection #0
"ACTIVE"
```

The requests do arrive in the http-request.log file
```
# tail -n 2000 /var/presto/data/var/log/http-request.log | grep PUT
2015-12-22T09:03:09.518Z	0:0:0:0:0:0:0:1	PUT	/v1/info/state	null	curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2	200	15	0	1	6f23007d-9472-4788-bc9e-6dfdeb9d58cb
2015-12-22T09:03:11.247Z	0:0:0:0:0:0:0:1	PUT	/v1/info/state	null	curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2	200	15	0	1	2d014835-c006-4728-b6bd-fbbab02c213c
2015-12-22T09:03:24.613Z	0:0:0:0:0:0:0:1	PUT	/v1/info/state	null	curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2	200	15	0	1	f1163297-5014-4ec7-b4b2-bb6b483cb690
```

The server.log file shows no indication of this event happening.

**Comment by RobinUS2** [comment]
The log on this line is nowhere to be found: https://github.com/facebook/presto/blob/fa763cf4fc8ab35824ee6a169a85833ad0adaba4/presto-main/src/main/java/com/facebook/presto/server/GracefulShutdownHandler.java#L75

**Comment by nezihyigitbasi** [comment]
@RobinUS2 I don't know why you don't see the info log in `GracefulShutdownHandler` (may be a problem with your logging configuration), but the only reason that I can think of why the node is still `ACTIVE` is you may be trying to shutdown the coordinator.

**Comment by RobinUS2** [comment]
@nezihyigitbasi That sounds indeed like what is/was happening. Wasn't aware of this behaviour, although it kind of makes sense. I think we should do two things:
- add the behaviour to the documentation
- let the API throw an appropriate exception/error if you try to shutdown a coordinator

**Comment by nezihyigitbasi** [comment]
@cberner what do you think? I think we should update the docs for sure. But regarding throwing an exception, I remember like that was the case for the initial implementation but then we removed that IIRC for the sake of idempotency.

**Comment by cberner** [comment]
I think it's fine to throw an exception if it's the coordinator. It just shouldn't throw an exception for workers. Even of it's already shutting down
