### ISSUE TITLE
Reducing verbosity of http-request.log

### ISSUE THREAD

**Issue by HenryCook** [facebook/presto#4258]
The `http-request.log` is reaching in excess of 1GB in size, and has been unfortunately causing disk space issues.

Is it at all possible to reduce the verbosity of these logs?

I came across this [link] (https://groups.google.com/forum/#!searchin/presto-users/http-request$20log/presto-users/NovxmG9gjco/cE6uv0eS1KEJ) in the presto-users group however it's from 2014.

Any suggestions are welcome.

**Comment by cberner** [comment]
You can disable the log using `http-server.log.enabled=false`, or reduce the max file size with `http-server.log.max-size`. Does that answer your question?

**Comment by HenryCook** [comment]
If I were to set it to 100MB for example, would I put `http-server.log.max-size=100MB` in `config.properties`?

Thanks for your help so far.

**Comment by martint** [comment]
Yes. You may also want to set `log.max-history` to limit how many files to keep around.

**Comment by martint** [comment]
Yes. You may also want to set `http-server.log.max-history` to limit the number of files to keep around

**Comment by HenryCook** [comment]
That's great, thanks.

Really appreciate the help.
