### ISSUE TITLE
Connector properties are not propagated to Connectors in JdbcTable

### ISSUE THREAD

**Issue by sopel39** [facebook/presto#4317]
I have added support for decimal on `BigInteger` in TPCH connector. To do so, I have added additional schemas. Some of the schemas are `sf*_custom_decimal`. This schema contains TPCH tables with proper decimals that have precision and scale. Precision and scale can be specified by session properties (`custom_decimal_precision` and `custom_decimal_scale`). The problem is that those properties are not propagated to connector when using system tables (e.g. `ColumnJdbcTable`). This is because in `cursor` method `connectorSession` is converted to `Session` object using `FilterUtil.toSession` method. This erases any connector specific properties. I understand that `Session` object is required for further calls to `Metadata`. I tried to think of some elegant way of overcoming or avoiding this issue, but I think that requires some serious refactoring. What would be you suggestion or ideas?

FYI: @electrum

**Comment by electrum** [comment]
Put the decimal precision and scale in the table names, just like the TPCH scale factor.

**Comment by sopel39** [comment]
Yes, there are schemas with predefined precision and scale, but it is also very useful (e.g. when benchmarking) to be able to specify it at runtime. It's much easier than changing it in code, compiling and re-uploading Presto to cluster. I could make more predefined precision and scale pairs, but then the number of schemas in TPCH would be large. Maybe that's not a problem, but it would definitely make `show schemas from tpch` very user unfriendly. I would prefer to avoid that.

**Comment by electrum** [comment]
TPCH already has dynamic tables. You can query sf123 for example.

**Comment by electrum** [comment]
Sorry, I meant to say schema name, not table name.

**Comment by sopel39** [comment]
OK, I did as you described
