### ISSUE TITLE
Do not allow calling procedure in read-only mode

### ISSUE THREAD

**Issue by electrum** [facebook/presto#4328]
`CallTask` should have an additional check to prevent running a procedure in read-only mode, since the expected use of procedures is to modify some system or connector state.

This probably requires another method `isReadOnly()` added to `QueryStateMachine` that delegates to some additional methods in `TransactionManager` and `TransactionMetadata`.

**Comment by martint** [comment]
I don't think that's not generally true for sql procedures as described in the SQL standard, which allows for procedures that return values but don't allow modifying data.

**Comment by electrum** [comment]
When we implement that, we could allow procedures to specify if they should allow read only. But since they can't return values, it is best to assume they modify state.

**Comment by harunurhan** [comment]
@electrum 
Isn't having a transaction the only way to set read-only true? If yes procedures can't already be called in a transaction. 
Sorry If I am missing something so obvious.

**Comment by electrum** [comment]
@harunurhan Thanks, you're right, this isn't needed until we support read-only for autocommit mode. I'll update #4329 to mention procedures.
