### ISSUE TITLE
airlift version change breaks build

### ISSUE THREAD

**Issue by jxiang** [facebook/presto#4330]
[ERROR] presto-main/src/test/java/com/facebook/presto/operator/TestExchangeClient.java:[174,187] incompatible types: com.facebook.presto.operator.MockExchangeRequestProcessor cannot be converted to io.airlift.http.client.testing.TestingHttpClient.Processor
[ERROR] presto-main/src/test/java/com/facebook/presto/operator/TestExchangeClient.java:[247,187] incompatible types: com.facebook.presto.operator.MockExchangeRequestProcessor cannot be converted to io.airlift.http.client.testing.TestingHttpClient.Processor

**Comment by electrum** [comment]
Do you have the latest Presto version that uses 0.123 (not snapshot)?

**Comment by electrum** [comment]
It builds in Travis: https://travis-ci.org/facebook/presto

Please reopen if you still see issues with the latest master.

**Comment by jxiang** [comment]
No. I only have the latest snapshot version. By the way, after I moved back to commit 95883b0befb55d7, presto-main builds fine again.

**Comment by electrum** [comment]
Update to 8cd98206

**Comment by jxiang** [comment]
Cool. That works. Thanks.
