### ISSUE TITLE
Pre-compile regex patterns in BinaryLiteral

### ISSUE THREAD

**Issue by electrum** [facebook/presto#4347]

**Comment by harunurhan** [comment]
I'd like to take this one but I have a question;
what you mean is that use Pattern.compile, then use compiled pattern to perform match and replace on the string, right?
If yes, I don't see how this makes difference here, since we are not able re-use compiled pattern (used only once)
@electrum

**Comment by electrum** [comment]
Yes, just introduce some constants for the `Pattern.compile(...)` calls. The patterns are constant and used in every constructor invocation.

**Comment by maciejgrzybek** [comment]
Should be closed.
CC: @electrum
