### ISSUE TITLE
Web UI query detail view doesn't show contents at Safari after 0.133 

### ISSUE THREAD

**Issue by miniway** [facebook/presto#4414]
Web UI doesn’t seems to work anymore at 0.133 in Safari (9.0.3) as it uses javascript lambda expression. It looks fine in Chrome(47.0.2526) and Firefox(43.0.4)

![screen shot 2016-01-22 at 1 31 08 pm](https://cloud.githubusercontent.com/assets/725129/12523555/71f13b34-c10c-11e5-945c-f05e97bb2a66.png)
![2179a69429124fbac0cf549003adf074](https://cloud.githubusercontent.com/assets/725129/12523560/79eaaa8c-c10c-11e5-99cd-15af6496fcb5.png)

**Comment by raghavsethi** [comment]
Merged #4416.
