### ISSUE TITLE
Validate column order when creating Hive tables

### ISSUE THREAD

**Issue by electrum** [facebook/presto#4421]
Partition columns for Hive tables are always at the end because Hive works that way. When creating a table, the creation should fail if the columns are not in the final order (having `CREATE TABLE` silently rearrange columns is quite unexpected).

We should use a new error code for this: `HIVE_COLUMN_ORDER_MISMATCH`

This should fail because the partition column is listed first, but will be at the end in the final table:
```
CREATE TABLE test (
  ds varchar,
  x bigint)
WITH (partitioned_by = ARRAY['ds']);
```

This should fail because the partition columns are listed in a different order than in the partition specification:
```
CREATE TABLE test (
  x bigint,
  type varchar,
  ds varchar)
WITH (partitioned_by = ARRAY['ds', 'type']);
```

**Comment by damiencarol** [comment]
It's a good feature.

**Comment by haozhun** [comment]
What about `CREATE TABLE AS SELECT`? Should they fail as well?
