### ISSUE TITLE
Disallow window functions in HAVING clause

### ISSUE THREAD

**Issue by cberner** [facebook/presto#4435]
```
select 1, rank() over() from (values (1)) t having rank() over () > 1
```
Fails with `rank():bigint is not a scalar function`. However, it should instead fail during analysis with a message like "window functions are not allowed in HAVING", as this is explicitly forbidden by the SQL spec (see section 7.10.5).
This should be done in `StatementAnalyzer.analyzeHaving` by visiting the expression and throwing a `SemanticException` if there's a window function present.

**Comment by martint** [comment]
Isn't this the same as https://github.com/facebook/presto/issues/3979?

**Comment by cberner** [comment]
Yes
