### ISSUE TITLE
Fix Hive AlreadyExists exceptions

### ISSUE THREAD

**Issue by electrum** [facebook/presto#4459]
This classes `TableAlreadyExistsException` and `ViewAlreadyExistsException` should extend `PrestoException` directly and use `ALREADY_EXISTS` as the error code.

**Comment by harunurhan** [comment]
I know that issue is only for TableAldreadyExistsException but I think it might be better to fix ViewAlreadyExistsException too. What do you think? @electrum

**Comment by maciejgrzybek** [comment]
This should be closed, don't you think @electrum?
