### ISSUE TITLE
Hive table is not visible for first query after rename

### ISSUE THREAD

**Issue by kokosing** [facebook/presto#4662]
```
presto> use hive.default;
presto:default> alter table t rename to t2;
RENAME TABLE
presto:default> select * from t2;
Query 20160229_132727_00038_hieyj failed: line 1:15: Table hive.default.t2 does not exist
select * from t2

presto:default> select * from t2;
 t 
---
(0 rows)

Query 20160229_132729_00039_hieyj, FINISHED, 1 node
Splits: 1 total, 1 done (100,00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

presto:default> 
```

**Comment by cawallin** [comment]
This is probably because the Hive metastore cache has not refreshed yet; do you have `hive.metastore-cache-ttl` set in `hive.properties`?

**Comment by kokosing** [comment]
Yes, setting ```hive.metastore-cache-ttl=0s``` fixes the problem. According to my understanding it is just a workaround. I think better solution would be if presto could invalidate metastore cache when it does write to it?

**Comment by kokosing** [comment]
@dain Thanks!

sob., 5.03.2016, 22:42 użytkownik Dain Sundstrom <notifications@github.com>
napisał:
