### ISSUE TITLE
Aggregate functions on Hive partitioned columns should run without reading underlying data

### ISSUE THREAD

**Issue by Downchuck** [facebook/presto#4703]
When tbl is partitioned by col, aggregates should not need to read the underlying data.
```sql
select max(col) from tbl
```

Note that using explain will show min and max simply through the planner. The current behavior reads all of the underlying data even though the field is virtual and only specified as metadata partitions.

**Comment by electrum** [comment]
We have this. Add the following to your coordinator config.properties:

  optimizer.optimize-metadata-queries=true

Note that this will return wrong answers if you have empty partitions (a normal aggregation would skip them because there are no rows to aggregate).

**Comment by Downchuck** [comment]
@electrum That makes sense, as a non-default flag. Could we get a default optimization which simply attempts to read one record in the underlying data -- that'd work without returning answers.
