### ISSUE TITLE
COUNT(*) query is not smart when used with LIMIT

### ISSUE THREAD

**Issue by shezarkhani** [facebook/presto#4725]
Having a catalog on top of Kafka, I tried these two scenarios:

Doing a pure select with a where clause returns in about 2 seconds.
`presto:default> select * from requests where country = 'US' limit 10;`

However, changing that to a `count` takes a very long time to complete.
`presto:default> select count(*) from requests where country= 'US' limit 10;`

It makes sense for presto to try and do a "full scan" in case there are less items than the `limit` specified. However, I think it could be smarter in the cases that a select query would return more result than the limit count.

**Comment by raghavsethi** [comment]
Actually, Presto's behavior makes sense. The `LIMIT` operator simply controls the number of rows returned. As count returns only one row, it is logically consistent that Presto would do the entire computation.

**Comment by harunurhan** [comment]
@shezarkhani 
`select count(*) from (select id from requests where country= 'US' limit 10)` should behave like you want.

**Comment by martint** [comment]
As explained by @raghavsethi, this is expected SQL behavior. Closing.
