### ISSUE TITLE
information_schema.tables.table_type has BASE TABLE instead of expected value TABLE

### ISSUE THREAD

**Issue by brian-rickman** [facebook/presto#4798]
This is also seen in JDBC `connection.getMetaData().getTableTypes()`.

    presto:default> select * from hive.information_schema.tables;
     table_catalog |    table_schema    |          table_name                         | table_type
    ---------------+--------------------+---------------------------------------------+------------
     hive          | information_schema | columns                                     | BASE TABLE
     hive          | information_schema | tables                                      | BASE TABLE
     hive          | information_schema | views                                       | BASE TABLE
     hive          | information_schema | schemata                                    | BASE TABLE
    ...

The current behavior breaks SAP Lumira and may affect other popular BI tools.

**Comment by damiencarol** [comment]
Your assumption is wrong. JDBC doesn't fix values.
This method exists only to discover auto-magicaly tables types.

**Comment by electrum** [comment]
This is correct for `information_schema`. See part 11 of the specification for "TABLES base table":
```
CREATE TABLE TABLES (
...
  TABLE_TYPE INFORMATION_SCHEMA.CHARACTER_DATA
    CONSTRAINT TABLE_TYPE_NOT_NULL
      NOT NULL
    CONSTRAINT TABLE_TYPE_CHECK
      CHECK ( TABLE_TYPE IN
            ( 'BASE TABLE', 'VIEW', 'GLOBAL TEMPORARY', 'LOCAL TEMPORARY' ) )
...

**Comment by electrum** [comment]
JDBC does expect `TABLE`:

https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getTables-java.lang.String-java.lang.String-java.lang.String-java.lang.String:A-

And Presto returns the correctly for `system.jdbc.tables` which is used for the JDBC driver:

https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/connector/system/jdbc/TableJdbcTable.java#L91

**Comment by electrum** [comment]
`system.jdbc.table_types` is also correct:
https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/connector/system/jdbc/TableTypeJdbcTable.java

**Comment by brian-rickman** [comment]
OK.  Thanks for looking into it.
