### ISSUE TITLE
LIKE statements case sensitive all of a sudden?

### ISSUE THREAD

**Issue by RobinUS2** [facebook/presto#4799]
Hi there,

It seems that presto suddenly became case sensitive for LIKE statements, which seems to be new.

Is this meant to be? Sounds like a breaking change because queries all of a sudden generate other results. See simple example below.

Thanks!

```
presto> with a as (select 'Robin' as c) select * from a where c like 'Rob%'
     -> ;
   c   
-------
 Robin 
(1 row)

Query 20160316_162550_02421_dwkpm, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

presto> with a as (select 'Robin' as c) select * from a where c like 'rob%';
 c 
---
(0 rows)

Query 20160316_162553_02422_dwkpm, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
```

**Comment by KBP-TDC** [comment]
@RobinUS2 : which version of Presto are you running now? and which version was it previously?

**Comment by electrum** [comment]
LIKE has always been case sensitive in Presto (per the SQL standard).

Is it possible you are thinking of MySQL, which uses case insensitive collation a by default?

**Comment by RobinUS2** [comment]
0.142 is the version, so for MySQL it's true indeed, but I thought presto had the same behavior before (we came from 0.141). 

Weird thing is that people all of sudden since today complain that their "old queries" return different results. 

Is there a way to make like statements case insensitive? Or should we wrap both sides of the statement in a lower() ?

**Comment by electrum** [comment]
You'll need to wrap both sides in `lower()`. I just ran this on 0.141:
```
presto> select 'HELLO' like '%e%';
 _col0 
-------
 false 
(1 row)

presto> select 'hello' like '%E%';
 _col0 
-------
 false 
(1 row)

**Comment by electrum** [comment]
I'm closing this given the above verification on 0.141. If you have counter-examples, please reopen.
